import type { SiteCopy } from '@/content/copy';
import { ERROR_PAGE } from '@/content/copy/error-page';

/**
 * The English interface copy (BRD, the English copy bank section; ADR-043): the same shape as
 * the Arabic bank, key for key. Brand: "B7R Print". Written by the agent; owed Dhia's read.
 */
export const en: SiteCopy = {
  a11y: {
    skipToContent: 'Skip to content',
    mainNavigation: 'Main navigation',
    footerNavigation: 'Footer links',
    homeLink: 'B7R Print, home',
    close: 'Close',
    loading: 'Loading',
    /** The language switch: named in the target language, described in this one. */
    switchLanguage: 'Switch to the Arabic site',
  },
  hero: {
    carouselLabel: 'Featured slides',
    slideIndicator: 'Slide {n} of {total}',
    pause: 'Pause the slideshow',
    resume: 'Resume the slideshow',
  },
  designer: {
    canvasLabel: 'Design preview on the product',
    productGroupLabel: 'Choose a product',
    colorGroupLabel: 'Choose a colour',
    colorOption: 'Colour {color}',
    sellPriceInput: 'Selling price in SAR',
    sellPriceSlider: 'Selling price',
    dailySalesDecrement: 'Fewer daily sales',
    dailySalesIncrement: 'More daily sales',
    designThumbnail: 'Current design',
    dropzoneLabel: 'Upload your design file',
    productGroup: 'Product',
    uploadPrompt: 'Tap to upload your logo or image',
    remove: 'Remove the design',
    canvasHint: 'Drag the design to move it; use the corners to resize.',
    baseCost: 'Cost from B7R',
    sellPrice: 'Selling price in your store',
    suggestedPrice: 'Suggested price',
    dailySales: 'Daily sales',
    perPiece: 'Your profit per piece',
    monthly: 'Your estimated monthly profit',
    negativeWarning: 'The selling price is below the cost. Raise it to make a profit.',
    fileError: 'The file is not supported or is larger than 10 MB.',
    mockupAlt: '{product} {color}, front view',
  },
  strip: {
    label: 'Available products',
    swipeHint: 'Swipe',
  },
  gallery: {
    label: 'Product photos',
    flip: 'Flip the photo',
    front: 'Front view',
    back: 'Back view',
  },
  breadcrumbs: {
    label: 'Page path',
  },
  compare: {
    caption: '{ours} compared with {theirs}',
    criterion: 'Criterion',
    bestFor: '{ours} is best for you if',
    notBestFor: '{ours} is not the best fit if',
    asOf: "{theirs}'s pages were read on",
    asOfTail: '; the numbers change, the read date stays true.',
  },
  faq: {
    groupsNav: 'Question groups',
    /** The group names as the page shows them; the select values (Appendix D) are the keys. */
    groups: {
      البداية: 'Getting started',
      'الأسعار والربح': 'Prices and profit',
      'الطلبات والتوصيل': 'Orders and delivery',
      'المتاجر والربط': 'Stores and connections',
      'الجودة والدعم': 'Quality and support',
    },
  },
  legal: {
    onThisPage: 'On this page',
    updatedPrefix: 'Last updated:',
  },
  share: {
    whatsapp: 'Share on WhatsApp',
    x: 'Share on X',
    copy: 'Copy the link',
  },
  testimonials: {
    placeholderTag: 'Sample',
  },
  integrations: {
    availableTag: 'Available now',
    tileAria: 'Connect a {platform} store',
  },
  productsPage: {
    title: 'Products',
    lead: 'Quality products, printed on demand and shipped under your store name.',
    pricePrefix: 'From',
    breadcrumbHome: 'Home',
    priceBlock: {
      cost: 'Cost from',
      suggested: 'Suggested selling price',
      profit: 'Your estimated profit',
      perPiece: 'per piece',
    },
    primaryCta: 'Start selling this product',
    secondaryLink: 'Try your design on it',
    sections: {
      specs: 'Specifications',
      sizeChart: 'Size chart',
      related: 'Other products',
    },
    specLabels: {
      material: 'Material',
      weight: 'Weight',
      sizes: 'Sizes',
      colors: 'Colours',
      printArea: 'Print area',
      printMethod: 'Print method',
    },
    weightUnit: 'g',
    /** Between the sizes and the colours in the spec list. */
    listSeparator: ', ',
    sizeChartHeaders: { size: 'Size', length: 'Length', chest: 'Chest width', sleeve: 'Sleeve' },
    sizeChartUnit: 'Measurements in cm',
    colorSwitchAria: 'Colour {colour}',
  },
  contactForm: {
    labels: {
      name: 'Name',
      phone: 'Mobile number',
      email: 'Email',
      inquiry: 'Inquiry type',
      message: 'Your message',
    },
    placeholders: {
      name: 'Your full name',
      phone: '05XXXXXXXX',
      email: 'name@example.com',
      message: 'Write your message here',
    },
    inquiryOptions: ['Merchant', 'Partnership', 'Investment', 'Other'],
    submit: 'Send the message',
    sending: 'Sending',
    success: 'We received your message. We will reply soon.',
    /** Secondary link on the success card (BRD 6.9). */
    successWhatsapp: 'Message us on WhatsApp',
    failure: 'The message could not be sent. Try again or message us on WhatsApp.',
    validation: {
      name: 'Enter your name',
      phone: 'Enter a valid mobile number',
      email: 'Enter a valid email address',
      inquiry: 'Choose the inquiry type',
      message: 'Write your message',
    },
  },
  contactEmail: {
    subject: 'New message from the website: {inquiryType}',
    replyOnWhatsapp: 'Reply on WhatsApp',
  },
  notFoundPage: {
    title: 'Page not found',
    text: 'The link seems to have changed or been removed.',
    button: 'Back to the home page',
  },
  footer: {
    linksTitle: 'Links',
    policiesTitle: 'Policies',
    newsletterTitle: 'Newsletter',
    newsletterLabel: 'Subscribe for what is new',
    newsletterPlaceholder: 'name@example.com',
    newsletterButton: 'Subscribe',
    newsletterSuccess: 'Subscribed. We will only send you what is new.',
    newsletterError: 'Enter a valid email address.',
    newsletterUnavailable: 'Subscriptions are unavailable right now; try again later.',
    socialAria: {
      x: 'B7R Print on X',
      instagram: 'B7R Print on Instagram',
      tiktok: 'B7R Print on TikTok',
      whatsapp: 'B7R Print on WhatsApp',
    },
    badgesCaption: 'Payment methods and verification bodies',
    copyright: '© {year} B7R Print. All rights reserved.',
  },
  draftBar: {
    label: 'Draft preview: what you see here is not published yet.',
    exit: 'Exit the preview',
  },
  whatsappWidget: {
    buttonAria: 'Chat with us on WhatsApp',
    title: 'B7R Print',
    subtitle: 'Support team',
    greeting: 'Hi 👋 How can we help?',
    action: 'Start a chat',
    prefilled: 'Hello, I would like to know more about B7R Print.',
    closeAria: 'Close',
  },
  consent: {
    text: 'We use cookies to improve your experience and measure how the site performs.',
    accept: 'Accept',
    reject: 'Decline',
    link: 'Privacy policy',
  },
  errorPage: ERROR_PAGE.en,
  gonePage: {
    title: 'This page was removed',
    text: 'The link seems to have changed or been removed.',
    button: 'Back to the home page',
  },
  blog: {
    title: 'The B7R blog',
    lead: 'Practical guides to starting your brand and selling printed products in Saudi Arabia.',
    metaTemplate: 'By {author} · {date} · {n} min read',
    takeawaysTitle: 'Key takeaways',
    relatedTitle: 'Related articles',
    share: 'Share',
    inPostCta: {
      title: 'Start your brand today',
      text: 'No capital, no stock.',
      button: 'Start your brand for free',
    },
    author: { name: 'Dhia', role: 'Founder of B7R Print' },
    allHubs: 'All',
    emptyHub: 'No articles in this section yet.',
    emptyAuthor: 'No articles yet.',
    copied: 'Link copied',
    toc: 'In this article',
    updatedPrefix: 'Updated',
    previousPost: 'Previous article',
    nextPost: 'Next article',
    featured: 'Latest article',
    latest: 'Latest articles',
    search: {
      label: 'Search the blog',
      placeholder: 'Type a word from a title',
      results: 'Search results',
      empty: 'No results. Try another word.',
      clear: 'Clear',
    },
    pagination: {
      label: 'Blog pages',
      page: 'Page {n}',
      previous: 'Newer',
      next: 'Older',
    },
    hubIntro: 'Every article in {hub}',
    authorIntro: 'Everything written by {name}',
    authorPosts: 'Articles',
  },
  seo: {
    titleTemplate: '%s | B7R Print',
    product: {
      title: '{name} for print on demand',
      description:
        '{short description}. Cost from SAR {base}, no minimum order, shipped under your store name.',
    },
    merchantCostNote: 'Merchant cost',
  },
  readingTime: {
    one: '1 min read',
    two: '2 min read',
    few: '{n} min read',
    many: '{n} min read',
  },
  media: {
    videoPosterAlt: 'A digital printer printing a design on a black T-shirt',
    trustBadges: {
      saudiBusinessCenter: 'Saudi Business Center',
      ministryOfCommerce: 'Ministry of Commerce',
      misk: 'Misk Foundation',
    },
    sarAria: 'Saudi riyal',
  },
  /** The `Intl` tag for dates: `14 September 2026`. */
  llms: {
    intro:
      "{brand} is a print-on-demand platform in Saudi Arabia: a merchant sells their design in their Salla, Zid or Shopify store, and we print the piece in {origin} and ship it under the store's name within {days} days at most inside the Kingdom. No stock and no minimum; the account is free with SAR {credit} of welcome credit.",
    pages: 'Pages',
    products: 'Products (merchant cost and suggested price in Saudi riyals)',
    productLine: '{description} Cost SAR {cost}, suggested price SAR {price}.',
    blog: 'Blog',
    otherLanguages: 'Other languages',
    otherLanguage: 'Arabic version',
  },
  dateLocale: 'en-GB',
};
