import type { SeedTopic } from '@/content/seed/topics';

/**
 * The English backlog (BRD Appendix E amendment, ADR-043): fifteen topics aimed at the
 * English prompts of BRD §7.7 (the questions an English-speaking merchant, creator or
 * investor asks an assistant about print on demand in Saudi Arabia). Same shape as the
 * Arabic backlog; the engine writes them on the English blog. Windows as `MM-DD` pairs. The
 * three the Level 1 posts already cover in English seed as `published` and linked, so the
 * engine never writes them twice (the dedupe would refuse them anyway).
 */
export const seedTopicsEn: Array<SeedTopic & { language: 'en' }> = [
  {
    language: 'en',
    title: 'How to start a clothing brand in Saudi Arabia with no factory and no stock',
    hub: 'getting-started',
    primaryKeyword: 'start a clothing brand in Saudi Arabia',
    secondaryKeywords: ['print on demand Saudi Arabia', 'sell t-shirts with no inventory'],
    intent: 'informational',
    priority: 5,
    post: 'start-clothing-brand-saudi-no-factory-no-stock',
  },
  {
    language: 'en',
    title: 'Print on demand in Saudi Arabia: how it works, what it costs, who it suits',
    hub: 'pod-basics',
    primaryKeyword: 'print on demand Saudi Arabia',
    secondaryKeywords: ['POD KSA', 'custom t-shirt printing Jeddah'],
    intent: 'informational',
    priority: 5,
    post: 'what-is-print-on-demand-saudi-examples',
  },
  {
    language: 'en',
    title: 'Print on demand vs dropshipping in the Gulf: which one fits your store?',
    hub: 'pod-basics',
    primaryKeyword: 'print on demand vs dropshipping',
    secondaryKeywords: ['dropshipping Saudi Arabia', 'no inventory business'],
    intent: 'informational',
    priority: 4,
  },
  {
    language: 'en',
    title:
      'Local print on demand vs Printful and Printify for Saudi customers: delivery, customs, cost',
    hub: 'pod-basics',
    primaryKeyword: 'Printful alternative Saudi Arabia',
    secondaryKeywords: ['Printify Saudi Arabia', 'print on demand Middle East'],
    intent: 'commercial',
    priority: 5,
  },
  {
    language: 'en',
    title: 'How long does delivery take? Local printing in Jeddah vs shipping from abroad',
    hub: 'pod-basics',
    primaryKeyword: 'print on demand delivery time Saudi Arabia',
    secondaryKeywords: ['shipping within Saudi Arabia', 'customs on printed goods'],
    intent: 'informational',
    priority: 4,
  },
  {
    language: 'en',
    title: 'Connect a Shopify store to print on demand in Saudi Arabia',
    hub: 'salla-zid-shopify',
    primaryKeyword: 'Shopify print on demand Saudi Arabia',
    secondaryKeywords: ['Shopify Saudi Arabia', 'print on demand app Shopify'],
    intent: 'commercial',
    priority: 5,
  },
  {
    language: 'en',
    title: 'What are Salla and Zid? A guide for founders selling into Saudi Arabia',
    hub: 'salla-zid-shopify',
    primaryKeyword: 'Salla and Zid',
    secondaryKeywords: ['Salla vs Shopify', 'Saudi e-commerce platforms'],
    intent: 'informational',
    priority: 4,
  },
  {
    language: 'en',
    title:
      'Print file requirements for on-demand apparel: size, resolution, transparent background',
    hub: 'design',
    primaryKeyword: 'print file requirements for t-shirts',
    secondaryKeywords: ['DTG print file size', '28 x 38 cm print area'],
    intent: 'informational',
    priority: 4,
  },
  {
    language: 'en',
    title: 'Designs that sell in Saudi Arabia: Arabic calligraphy, coffee, falcons and city pride',
    hub: 'design',
    primaryKeyword: 'Arabic t-shirt design ideas',
    secondaryKeywords: ['Saudi t-shirt designs', 'Arabic calligraphy merch'],
    intent: 'informational',
    priority: 4,
  },
  {
    language: 'en',
    title: 'Intellectual property for merch sellers in Saudi Arabia: what you cannot print',
    hub: 'design',
    primaryKeyword: 'trademark rules for printed merchandise',
    secondaryKeywords: ['copyright t-shirt designs', 'licensed merch Saudi Arabia'],
    intent: 'informational',
    priority: 3,
  },
  {
    language: 'en',
    title: 'How to price a printed t-shirt in Saudi Arabia: cost, shipping, VAT and margin',
    hub: 'pricing-profit',
    primaryKeyword: 'how to price a printed t-shirt',
    secondaryKeywords: ['t-shirt profit margin', 'print on demand pricing'],
    intent: 'informational',
    priority: 5,
    post: 'how-to-price-printed-tshirt-saudi',
  },
  {
    language: 'en',
    title: 'VAT and e-invoicing for a print-on-demand store in Saudi Arabia',
    hub: 'pricing-profit',
    primaryKeyword: 'VAT for online stores in Saudi Arabia',
    secondaryKeywords: ['ZATCA e-invoicing', 'small store tax Saudi Arabia'],
    intent: 'informational',
    priority: 3,
  },
  {
    language: 'en',
    title: 'Creator merch in Saudi Arabia: launch a line for your audience with no inventory',
    hub: 'getting-started',
    primaryKeyword: 'creator merch Saudi Arabia',
    secondaryKeywords: ['influencer merchandise', 'merch for content creators'],
    intent: 'commercial',
    priority: 4,
  },
  {
    language: 'en',
    title: 'Saudi National Day merch: prepare your store six weeks before 23 September',
    hub: 'seasons',
    primaryKeyword: 'Saudi National Day t-shirts',
    secondaryKeywords: ['National Day merch', 'September 23 designs'],
    intent: 'seasonal',
    priority: 4,
    window: { start: '06-15', end: '08-10' },
  },
  {
    language: 'en',
    title: 'Ramadan and Eid gifts on demand: timing and the designs that sell',
    hub: 'seasons',
    primaryKeyword: 'Ramadan merch ideas',
    secondaryKeywords: ['Eid gifts custom', 'Ramadan t-shirt designs'],
    intent: 'seasonal',
    priority: 4,
    window: { start: '2026-12-01', end: '2027-01-09' },
  },
];
