/**
 * The photo renditions (ADR-064): a `sizes_{format}{width}_*` group per rung of the ladder
 * in `src/lib/renditions.ts`, ten widths in AVIF and WebP, with the filename index Payload
 * puts on each. The four groups of the 2026-09-13 config (`thumbnail`, `card`, `hero`,
 * `og`), unread since `20260918_213027_media_no_renditions` left them "for a later
 * migration", go in the same pass: no image since then has listed them, so the running one
 * is unaffected. `focal_x` and `focal_y` stay: Payload keeps the two hidden fields whenever
 * `imageSizes` is set, whatever `focalPoint` says (`uploads/getBaseFields.js`), and the
 * running image still selects them. `down()` removes the new groups only: the old ones were
 * unread since 2026-09-18 and are not restored.
 */
import { type MigrateDownArgs, type MigrateUpArgs, sql } from '@payloadcms/db-postgres';

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "media" ADD COLUMN "sizes_avif128_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif128_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif128_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif128_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif128_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif128_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif384_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif384_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif384_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif384_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif384_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif384_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif640_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif640_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif640_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif640_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif640_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif640_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif828_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif828_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif828_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif828_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif828_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif828_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1080_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1080_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1080_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1080_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1080_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1080_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1200_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1200_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1200_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1200_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1200_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1200_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1536_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1536_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1536_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1536_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1536_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1536_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1920_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1920_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1920_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1920_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1920_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif1920_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif2560_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif2560_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif2560_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif2560_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif2560_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif2560_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif3840_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif3840_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif3840_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif3840_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_avif3840_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_avif3840_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp128_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp128_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp128_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp128_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp128_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp128_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp384_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp384_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp384_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp384_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp384_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp384_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp640_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp640_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp640_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp640_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp640_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp640_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp828_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp828_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp828_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp828_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp828_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp828_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1080_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1080_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1080_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1080_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1080_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1080_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1200_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1200_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1200_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1200_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1200_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1200_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1536_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1536_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1536_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1536_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1536_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1536_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1920_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1920_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1920_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1920_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1920_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp1920_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp2560_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp2560_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp2560_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp2560_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp2560_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp2560_filename" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp3840_url" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp3840_width" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp3840_height" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp3840_mime_type" varchar;
  ALTER TABLE "media" ADD COLUMN "sizes_webp3840_filesize" numeric;
  ALTER TABLE "media" ADD COLUMN "sizes_webp3840_filename" varchar;
  CREATE INDEX "media_sizes_avif128_sizes_avif128_filename_idx" ON "media" USING btree ("sizes_avif128_filename");
  CREATE INDEX "media_sizes_avif384_sizes_avif384_filename_idx" ON "media" USING btree ("sizes_avif384_filename");
  CREATE INDEX "media_sizes_avif640_sizes_avif640_filename_idx" ON "media" USING btree ("sizes_avif640_filename");
  CREATE INDEX "media_sizes_avif828_sizes_avif828_filename_idx" ON "media" USING btree ("sizes_avif828_filename");
  CREATE INDEX "media_sizes_avif1080_sizes_avif1080_filename_idx" ON "media" USING btree ("sizes_avif1080_filename");
  CREATE INDEX "media_sizes_avif1200_sizes_avif1200_filename_idx" ON "media" USING btree ("sizes_avif1200_filename");
  CREATE INDEX "media_sizes_avif1536_sizes_avif1536_filename_idx" ON "media" USING btree ("sizes_avif1536_filename");
  CREATE INDEX "media_sizes_avif1920_sizes_avif1920_filename_idx" ON "media" USING btree ("sizes_avif1920_filename");
  CREATE INDEX "media_sizes_avif2560_sizes_avif2560_filename_idx" ON "media" USING btree ("sizes_avif2560_filename");
  CREATE INDEX "media_sizes_avif3840_sizes_avif3840_filename_idx" ON "media" USING btree ("sizes_avif3840_filename");
  CREATE INDEX "media_sizes_webp128_sizes_webp128_filename_idx" ON "media" USING btree ("sizes_webp128_filename");
  CREATE INDEX "media_sizes_webp384_sizes_webp384_filename_idx" ON "media" USING btree ("sizes_webp384_filename");
  CREATE INDEX "media_sizes_webp640_sizes_webp640_filename_idx" ON "media" USING btree ("sizes_webp640_filename");
  CREATE INDEX "media_sizes_webp828_sizes_webp828_filename_idx" ON "media" USING btree ("sizes_webp828_filename");
  CREATE INDEX "media_sizes_webp1080_sizes_webp1080_filename_idx" ON "media" USING btree ("sizes_webp1080_filename");
  CREATE INDEX "media_sizes_webp1200_sizes_webp1200_filename_idx" ON "media" USING btree ("sizes_webp1200_filename");
  CREATE INDEX "media_sizes_webp1536_sizes_webp1536_filename_idx" ON "media" USING btree ("sizes_webp1536_filename");
  CREATE INDEX "media_sizes_webp1920_sizes_webp1920_filename_idx" ON "media" USING btree ("sizes_webp1920_filename");
  CREATE INDEX "media_sizes_webp2560_sizes_webp2560_filename_idx" ON "media" USING btree ("sizes_webp2560_filename");
  CREATE INDEX "media_sizes_webp3840_sizes_webp3840_filename_idx" ON "media" USING btree ("sizes_webp3840_filename");
  DROP INDEX IF EXISTS "media_sizes_thumbnail_sizes_thumbnail_filename_idx";
  DROP INDEX IF EXISTS "media_sizes_card_sizes_card_filename_idx";
  DROP INDEX IF EXISTS "media_sizes_hero_sizes_hero_filename_idx";
  DROP INDEX IF EXISTS "media_sizes_og_sizes_og_filename_idx";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_thumbnail_url";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_thumbnail_width";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_thumbnail_height";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_thumbnail_mime_type";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_thumbnail_filesize";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_thumbnail_filename";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_card_url";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_card_width";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_card_height";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_card_mime_type";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_card_filesize";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_card_filename";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_hero_url";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_hero_width";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_hero_height";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_hero_mime_type";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_hero_filesize";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_hero_filename";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_og_url";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_og_width";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_og_height";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_og_mime_type";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_og_filesize";
  ALTER TABLE "media" DROP COLUMN IF EXISTS "sizes_og_filename";`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP INDEX "media_sizes_avif128_sizes_avif128_filename_idx";
  DROP INDEX "media_sizes_avif384_sizes_avif384_filename_idx";
  DROP INDEX "media_sizes_avif640_sizes_avif640_filename_idx";
  DROP INDEX "media_sizes_avif828_sizes_avif828_filename_idx";
  DROP INDEX "media_sizes_avif1080_sizes_avif1080_filename_idx";
  DROP INDEX "media_sizes_avif1200_sizes_avif1200_filename_idx";
  DROP INDEX "media_sizes_avif1536_sizes_avif1536_filename_idx";
  DROP INDEX "media_sizes_avif1920_sizes_avif1920_filename_idx";
  DROP INDEX "media_sizes_avif2560_sizes_avif2560_filename_idx";
  DROP INDEX "media_sizes_avif3840_sizes_avif3840_filename_idx";
  DROP INDEX "media_sizes_webp128_sizes_webp128_filename_idx";
  DROP INDEX "media_sizes_webp384_sizes_webp384_filename_idx";
  DROP INDEX "media_sizes_webp640_sizes_webp640_filename_idx";
  DROP INDEX "media_sizes_webp828_sizes_webp828_filename_idx";
  DROP INDEX "media_sizes_webp1080_sizes_webp1080_filename_idx";
  DROP INDEX "media_sizes_webp1200_sizes_webp1200_filename_idx";
  DROP INDEX "media_sizes_webp1536_sizes_webp1536_filename_idx";
  DROP INDEX "media_sizes_webp1920_sizes_webp1920_filename_idx";
  DROP INDEX "media_sizes_webp2560_sizes_webp2560_filename_idx";
  DROP INDEX "media_sizes_webp3840_sizes_webp3840_filename_idx";
  ALTER TABLE "media" DROP COLUMN "sizes_avif128_url";
  ALTER TABLE "media" DROP COLUMN "sizes_avif128_width";
  ALTER TABLE "media" DROP COLUMN "sizes_avif128_height";
  ALTER TABLE "media" DROP COLUMN "sizes_avif128_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_avif128_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_avif128_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_avif384_url";
  ALTER TABLE "media" DROP COLUMN "sizes_avif384_width";
  ALTER TABLE "media" DROP COLUMN "sizes_avif384_height";
  ALTER TABLE "media" DROP COLUMN "sizes_avif384_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_avif384_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_avif384_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_avif640_url";
  ALTER TABLE "media" DROP COLUMN "sizes_avif640_width";
  ALTER TABLE "media" DROP COLUMN "sizes_avif640_height";
  ALTER TABLE "media" DROP COLUMN "sizes_avif640_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_avif640_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_avif640_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_avif828_url";
  ALTER TABLE "media" DROP COLUMN "sizes_avif828_width";
  ALTER TABLE "media" DROP COLUMN "sizes_avif828_height";
  ALTER TABLE "media" DROP COLUMN "sizes_avif828_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_avif828_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_avif828_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1080_url";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1080_width";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1080_height";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1080_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1080_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1080_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1200_url";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1200_width";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1200_height";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1200_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1200_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1200_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1536_url";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1536_width";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1536_height";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1536_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1536_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1536_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1920_url";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1920_width";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1920_height";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1920_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1920_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_avif1920_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_avif2560_url";
  ALTER TABLE "media" DROP COLUMN "sizes_avif2560_width";
  ALTER TABLE "media" DROP COLUMN "sizes_avif2560_height";
  ALTER TABLE "media" DROP COLUMN "sizes_avif2560_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_avif2560_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_avif2560_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_avif3840_url";
  ALTER TABLE "media" DROP COLUMN "sizes_avif3840_width";
  ALTER TABLE "media" DROP COLUMN "sizes_avif3840_height";
  ALTER TABLE "media" DROP COLUMN "sizes_avif3840_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_avif3840_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_avif3840_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_webp128_url";
  ALTER TABLE "media" DROP COLUMN "sizes_webp128_width";
  ALTER TABLE "media" DROP COLUMN "sizes_webp128_height";
  ALTER TABLE "media" DROP COLUMN "sizes_webp128_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_webp128_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_webp128_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_webp384_url";
  ALTER TABLE "media" DROP COLUMN "sizes_webp384_width";
  ALTER TABLE "media" DROP COLUMN "sizes_webp384_height";
  ALTER TABLE "media" DROP COLUMN "sizes_webp384_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_webp384_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_webp384_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_webp640_url";
  ALTER TABLE "media" DROP COLUMN "sizes_webp640_width";
  ALTER TABLE "media" DROP COLUMN "sizes_webp640_height";
  ALTER TABLE "media" DROP COLUMN "sizes_webp640_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_webp640_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_webp640_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_webp828_url";
  ALTER TABLE "media" DROP COLUMN "sizes_webp828_width";
  ALTER TABLE "media" DROP COLUMN "sizes_webp828_height";
  ALTER TABLE "media" DROP COLUMN "sizes_webp828_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_webp828_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_webp828_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1080_url";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1080_width";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1080_height";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1080_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1080_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1080_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1200_url";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1200_width";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1200_height";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1200_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1200_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1200_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1536_url";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1536_width";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1536_height";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1536_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1536_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1536_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1920_url";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1920_width";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1920_height";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1920_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1920_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_webp1920_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_webp2560_url";
  ALTER TABLE "media" DROP COLUMN "sizes_webp2560_width";
  ALTER TABLE "media" DROP COLUMN "sizes_webp2560_height";
  ALTER TABLE "media" DROP COLUMN "sizes_webp2560_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_webp2560_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_webp2560_filename";
  ALTER TABLE "media" DROP COLUMN "sizes_webp3840_url";
  ALTER TABLE "media" DROP COLUMN "sizes_webp3840_width";
  ALTER TABLE "media" DROP COLUMN "sizes_webp3840_height";
  ALTER TABLE "media" DROP COLUMN "sizes_webp3840_mime_type";
  ALTER TABLE "media" DROP COLUMN "sizes_webp3840_filesize";
  ALTER TABLE "media" DROP COLUMN "sizes_webp3840_filename";`)
}
