"""Traces the brand logo into one SVG path per brand blue (spec 010, phase 1d).

`resources/brand/logo/logo.png` and `icon.png` are flat three-colour artwork: every opaque
pixel is assigned to the nearest of the logo's three blues (the primary, the accent and the
primary dark), each colour traced with potrace, and the curves written as path data at whole
units (the artwork is about 2700 units wide and drawn at 130 px or less, so a decimal buys
nothing visible). Three files come out:

- `public/images/logo/sprite.svg`: the logo and the mark as two symbols, each path filled
  with `var(--logo-*, var(--color-*))`, which the shell draws with `<use>` and the browser
  caches once for every page. No path data reaches a page's HTML or JavaScript.
- `src/modules/core/logo-box.ts`: the two view boxes and the sprite's URL, with a hash of its
  contents so a new trace is a new URL.
- `src/modules/core/mark-paths.ts`: the mark's paths for the app icons, drawn on the server.

Run with uv, after the logo files change:

    uvx --with potracer --with numpy --with pillow python scripts/trace-logo.py
    pnpm format

Deterministic: the same PNGs give the same files once formatted.
"""

import hashlib
import json
from pathlib import Path

import numpy as np
import potrace
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
LOGO = ROOT / "resources/brand/logo"
SPRITE = ROOT / "public/images/logo/sprite.svg"
BOX = ROOT / "src/modules/core/logo-box.ts"
MARK_PATHS = ROOT / "src/modules/core/mark-paths.ts"
SPRITE_URL = "/images/logo/sprite.svg"

# The logo's own three blues; the shell paints each with the token it stands for.
LAYERS = {
    "primary": (1, 92, 181),
    "accent": (1, 156, 230),
    "primaryDark": (30, 94, 172),
}


# The token each blue is painted with, and the property a wrapper sets to repaint it.
TOKENS = {"primary": "primary", "accent": "accent", "primaryDark": "primary-dark"}


def fmt(value: float) -> str:
    return str(round(value))


def path_of(mask: np.ndarray) -> str:
    # potracer traces the dark pixels, so the mask is inverted: its pixels become the shapes.
    curves = potrace.Bitmap(~mask).trace(
        turdsize=8, alphamax=0.9, opticurve=True, opttolerance=0.2
    )
    parts: list[str] = []
    for curve in curves:
        parts.append(f"M{fmt(curve.start_point.x)} {fmt(curve.start_point.y)}")
        for seg in curve.segments:
            if seg.is_corner:
                parts.append(
                    f"L{fmt(seg.c.x)} {fmt(seg.c.y)}L{fmt(seg.end_point.x)} {fmt(seg.end_point.y)}"
                )
            else:
                parts.append(
                    f"C{fmt(seg.c1.x)} {fmt(seg.c1.y)} {fmt(seg.c2.x)} {fmt(seg.c2.y)} "
                    f"{fmt(seg.end_point.x)} {fmt(seg.end_point.y)}"
                )
        parts.append("Z")
    return "".join(parts)


def trace(file: str) -> dict:
    image = Image.open(LOGO / file).convert("RGBA")
    pixels = np.asarray(image).astype(np.float64)
    rgb, alpha = pixels[..., :3], pixels[..., 3]
    names = list(LAYERS)
    centres = np.array([LAYERS[name] for name in names], dtype=np.float64)
    nearest = ((rgb[..., None, :] - centres[None, None, :, :]) ** 2).sum(-1).argmin(-1)
    opaque = alpha > 127
    paths = {}
    for index, name in enumerate(names):
        mask = opaque & (nearest == index)
        if mask.any():
            paths[name] = path_of(mask)
    return {"width": image.width, "height": image.height, "paths": paths}


def symbol(name: str, art: dict) -> str:
    paths = "".join(
        f'<path fill-rule="evenodd" style="fill:var(--logo-{TOKENS[layer]}, var(--color-{TOKENS[layer]}))" d="{d}"/>'
        for layer, d in art["paths"].items()
    )
    return f'<symbol id="{name}" viewBox="0 0 {art["width"]} {art["height"]}">{paths}</symbol>'


BOX_TEMPLATE = """/**
 * The drawn logo's view boxes and its sprite (spec 010, phase 1d). Generated by
 * `scripts/trace-logo.py`; do not edit by hand. The paths live in the sprite, which the
 * browser caches once; the hash in its URL changes with a new trace.
 */
export const LOGO_BOX = {{ width: {logo_w}, height: {logo_h} }} as const;

export const MARK_BOX = {{ width: {mark_w}, height: {mark_h} }} as const;

export const LOGO_SPRITE = '{url}?v={version}';
"""

MARK_TEMPLATE = """import 'server-only';

/**
 * The mark's paths, one per brand blue, for the app icons drawn on the server (spec 010,
 * phase 1d). Generated by `scripts/trace-logo.py`; do not edit by hand. Server only, so the
 * path data never reaches a page's JavaScript.
 */
export const MARK = {mark} as const;
"""


def write(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8", newline="\n")
    print(f"trace-logo: wrote {path.relative_to(ROOT)} ({len(text)} bytes)")


def main() -> None:
    logo, mark = trace("logo.png"), trace("icon.png")
    sprite = (
        '<svg xmlns="http://www.w3.org/2000/svg">'
        + symbol("b7r-logo", logo)
        + symbol("b7r-mark", mark)
        + "</svg>\n"
    )
    write(SPRITE, sprite)
    version = hashlib.sha256(sprite.encode("utf-8")).hexdigest()[:10]
    box = BOX_TEMPLATE.format(
        logo_w=logo["width"],
        logo_h=logo["height"],
        mark_w=mark["width"],
        mark_h=mark["height"],
        url=SPRITE_URL,
        version=version,
    )
    write(BOX, box)
    write(MARK_PATHS, MARK_TEMPLATE.format(mark=json.dumps(mark, indent=2)))


if __name__ == "__main__":
    main()
