"""Traces the brand logo into one SVG path per brand blue (spec 010, phase 1d).

`resources/brand/logo/logo.png` and `icon.png` are flat three-colour artwork: every opaque
pixel is assigned to the nearest of the logo's three blues (the primary, the accent and the
primary dark), each colour traced with potrace, and the curves written as path data at one
decimal into `src/modules/core/logo-paths.ts`, which the shell draws with the fills bound to
the brand's tokens. Run with uv, after the logo files change:

    uvx --with potracer --with numpy --with pillow python scripts/trace-logo.py
    pnpm format

Deterministic: the same PNGs give the same file once formatted.
"""

import json
from pathlib import Path

import numpy as np
import potrace
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
LOGO = ROOT / 'resources/brand/logo'
OUT = ROOT / 'src/modules/core/logo-paths.ts'

# The logo's own three blues; the shell paints each with the token it stands for.
LAYERS = {
    'primary': (1, 92, 181),
    'accent': (1, 156, 230),
    'primaryDark': (30, 94, 172),
}


def fmt(value: float) -> str:
    text = f'{value:.1f}'
    return text[:-2] if text.endswith('.0') else text


def path_of(mask: np.ndarray) -> str:
    # potracer traces the dark pixels, so the mask is inverted: its pixels become the shapes.
    curves = potrace.Bitmap(~mask).trace(turdsize=8, alphamax=0.9, opticurve=True, opttolerance=0.2)
    parts: list[str] = []
    for curve in curves:
        parts.append(f'M{fmt(curve.start_point.x)} {fmt(curve.start_point.y)}')
        for seg in curve.segments:
            if seg.is_corner:
                parts.append(
                    f'L{fmt(seg.c.x)} {fmt(seg.c.y)}L{fmt(seg.end_point.x)} {fmt(seg.end_point.y)}'
                )
            else:
                parts.append(
                    f'C{fmt(seg.c1.x)} {fmt(seg.c1.y)} {fmt(seg.c2.x)} {fmt(seg.c2.y)} '
                    f'{fmt(seg.end_point.x)} {fmt(seg.end_point.y)}'
                )
        parts.append('Z')
    return ''.join(parts)


def trace(file: str) -> dict:
    image = Image.open(LOGO / file).convert('RGBA')
    pixels = np.asarray(image).astype(np.float64)
    rgb, alpha = pixels[..., :3], pixels[..., 3]
    names = list(LAYERS)
    centres = np.array([LAYERS[name] for name in names], dtype=np.float64)
    nearest = ((rgb[..., None, :] - centres[None, None, :, :]) ** 2).sum(-1).argmin(-1)
    opaque = alpha > 127
    paths = {}
    for index, name in enumerate(names):
        mask = opaque & (nearest == index)
        if mask.any():
            paths[name] = path_of(mask)
    return {'width': image.width, 'height': image.height, 'paths': paths}


def main() -> None:
    logo, mark = trace('logo.png'), trace('icon.png')
    header = (
        '/**\n'
        ' * The brand logo and its square mark as vector paths, one per brand blue (spec 010,\n'
        ' * phase 1d). Generated by `scripts/trace-logo.py` from `resources/brand/logo/logo.png`\n'
        ' * and `icon.png`; do not edit by hand. `BrandLogo` paints each path with its token, so\n'
        ' * the logo follows the Appearance screen.\n'
        ' */\n'
    )
    body = (
        f'export const LOGO = {json.dumps(logo, indent=2)} as const;\n\n'
        f'export const MARK = {json.dumps(mark, indent=2)} as const;\n'
    )
    OUT.write_text(header + body, encoding='utf-8', newline='\n')
    total = sum(len(p) for p in logo['paths'].values()) + sum(len(p) for p in mark['paths'].values())
    print(f'trace-logo: wrote {OUT.relative_to(ROOT)} ({total} bytes of path data)')


if __name__ == '__main__':
    main()
