export { CtaRibbon } from '@/modules/core/cta-ribbon';
export { Footer, newsletterCopy } from '@/modules/core/footer';
export { Header } from '@/modules/core/header/header';
export { SkipLink } from '@/modules/core/skip-link';
export { StatusPage } from '@/modules/core/status-page';
export { WaveDivider } from '@/modules/core/wave-divider';
export { track, trackEvent, registerSink, type TrackEvent } from '@/modules/core/analytics/track';
export { AnalyticsBridge, announceConsent } from '@/modules/core/analytics/analytics-bridge';
export { NearViewport, AfterDelay } from '@/modules/core/lazy-mount';
export { buildMetadata } from '@/modules/core/seo/metadata';
