/**
 * The drawn logo's view boxes and its sprite (spec 010, phase 1d). Generated by
 * `scripts/trace-logo.py`; do not edit by hand. The paths live in the sprite, which the
 * browser caches once; the hash in its URL changes with a new trace.
 */
export const LOGO_BOX = { width: 2713, height: 988 } as const;

export const MARK_BOX = { width: 988, height: 988 } as const;

export const LOGO_SPRITE = '/images/logo/sprite.svg?v=013c663a98';
