/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    pages: Page;
    faqs: Faq;
    testimonials: Testimonial;
    integrations: Integration;
    posts: Post;
    categories: Category;
    authors: Author;
    tags: Tag;
    'ai-topics': AiTopic;
    'ai-runs': AiRun;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    integrations: IntegrationsSelect<false> | IntegrationsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'ai-topics': AiTopicsSelect<false> | AiTopicsSelect<true>;
    'ai-runs': AiRunsSelect<false> | AiRunsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ar' | 'en') | ('ar' | 'en')[];
  globals: {
    home: Home;
    'site-settings': SiteSetting;
    navigation: Navigation;
    'seo-defaults': SeoDefault;
    'ai-settings': AiSetting;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
    'ai-settings': AiSettingsSelect<false> | AiSettingsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: 'ar' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'indexnow-ping': TaskIndexnowPing;
      'content-tick': TaskContentTick;
      'content-freshness': TaskContentFreshness;
      'content-digest': TaskContentDigest;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: {
      generatePost: WorkflowGeneratePost;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Panel accounts. Editors change content; admins also change settings and users.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Admins can do everything; editors edit content only.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Images and files used by pages and products. Give every image alt text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image in the language of the open locale tab; required.
   */
  alt: string;
  credit?: string | null;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Products on the site and in the designer: prices, photos, sizes and colours.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  /**
   * lowercase-hyphenated
   */
  slug: string;
  /**
   * One line for cards and meta
   */
  shortDescription: string;
  description: string;
  /**
   * Must match the app; there is no automatic sync.
   */
  baseCost: number;
  /**
   * Must match the app; there is no automatic sync.
   */
  suggestedPrice: number;
  sortOrder: number;
  colors: {
    slug: string;
    name: string;
    hex: string;
    front: number | Media;
    back?: (number | null) | Media;
    id?: string | null;
  }[];
  sizes: {
    label: string;
    length?: number | null;
    chest?: number | null;
    sleeve?: number | null;
    id?: string | null;
  }[];
  /**
   * e.g. S – 2XL
   */
  sizesSummary: string;
  material: string;
  weightGrams: number;
  printArea: {
    label: string;
    widthCm: number;
    heightCm: number;
    /**
     * Where the print area sits over the product photo in the designer.
     */
    canvas: {
      x: number;
      y: number;
      w: number;
      h: number;
    };
  };
  printMethodLabel: string;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Site pages as editable blocks. The seven designed pages keep their URLs; add new ones freely.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * lowercase-hyphenated; served at /slug
   */
  slug: string;
  lead?: string | null;
  blocks: (
    | {
        title?: string | null;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        heading: string;
        text: string;
        line: string;
        photo: number | Media;
        /**
         * The welcome credit and the why-us pairs from the home page
         */
        withFacts?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'story';
      }
    | {
        title?: string | null;
        items: {
          icon: 'ShieldCheck' | 'Workflow' | 'Zap' | 'Target' | 'Eye' | 'Heart';
          title: string;
          text: string;
          art?: (number | null) | Media;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'cards';
      }
    | {
        items: {
          title: string;
          text: string;
          icon: number | Media;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'steps';
      }
    | {
        title: string;
        sell: string;
        base: string;
        profit: string;
        exampleLine: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'profitEquation';
      }
    | {
        selection: 'all' | 'home';
        offset?: number | null;
        limit?: number | null;
        title?: string | null;
        linkLabel?: string | null;
        linkHref?: string | null;
        bottomLine?: string | null;
        bottomLinkWord?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faqList';
      }
    | {
        title: string;
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'miskCredential';
      }
    | {
        whatsappTitle: string;
        whatsappText: string;
        emailTitle: string;
        phoneTitle: string;
        followTitle: string;
        booking: {
          title: string;
          text: string;
          button: string;
          whatsappMessage: string;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'contact';
      }
    | {
        updatedAt: string;
        /**
         * ## headings become the on-this-page list; no HTML.
         */
        body: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'legalBody';
      }
    | {
        media: number | Media;
        caption?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaBanner';
      }
  )[];
  seo: {
    title: string;
    description: string;
    ogImage?: (number | null) | Media;
  };
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * FAQ entries by group. Up to five show on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  /**
   * Plain text, no links
   */
  answer: string;
  group: 'البداية' | 'الأسعار والربح' | 'الطلبات والتوصيل' | 'المتاجر والربط' | 'الجودة والدعم';
  order: number;
  /**
   * At most 5 entries
   */
  showOnHome?: boolean | null;
  homeOrder?: number | null;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Merchant quotes on the home page. Placeholders never show on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  name: string;
  store: string;
  avatar?: (number | null) | Media;
  order: number;
  /**
   * Placeholders show a «sample» badge on previews and are omitted on b7r.sa until a real entry exists.
   */
  placeholder?: boolean | null;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Connected platforms (Salla, Zid, Shopify) and their order in the integrations strip.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations".
 */
export interface Integration {
  id: number;
  /**
   * Selects the logo shown on the site
   */
  platform: 'salla' | 'zid' | 'shopify';
  order: number;
  name: string;
  nameLatin: string;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog posts. Drafts stay private; publishing needs a cover, three takeaways and two internal links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * lowercase-hyphenated; served at /blog/slug
   */
  slug: string;
  /**
   * One or two sentences on the post card and in search results.
   */
  excerpt: string;
  hub: number | Category;
  tags?: (number | Tag)[] | null;
  /**
   * The cover with its Arabic alt text in the library.
   */
  cover: number | Media;
  takeaways: {
    text: string;
    id?: string | null;
  }[];
  /**
   * H2s as questions, short paragraphs, at least two links to pages of this site.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author: number | Author;
  /**
   * Filled on the first publish when left empty.
   */
  publishedAt?: string | null;
  /**
   * Shown on the post when its content really changed.
   */
  contentUpdatedAt?: string | null;
  readingMinutes?: number | null;
  /**
   * A change by an editor to an engine post marks it "engine, then edited" and exempts it from the freshness job.
   */
  origin: 'manual' | 'ai' | 'ai-edited';
  factsBaseline?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  warnings?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional: the title and the excerpt are used when left empty.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The six blog hubs. Each has its own page, description and default cover.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * lowercase-hyphenated; served at /blog/category/slug
   */
  slug: string;
  /**
   * One sentence under the hub title and on the blog cards.
   */
  description: string;
  lead?: string | null;
  /**
   * Used when a post has no cover of its own.
   */
  defaultCover?: (number | null) | Media;
  order: number;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Optional tags that connect related posts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * lowercase-hyphenated
   */
  slug: string;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Who signs the blog posts. Each author has a page on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * lowercase-hyphenated; served at /author/slug
   */
  slug: string;
  /**
   * For example: founder of B7R Print
   */
  role: string;
  bio?: string | null;
  photo?: (number | null) | Media;
  /**
   * Public profiles (X, LinkedIn…) for the structured data of the page.
   */
  sameAs?:
    | {
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * What the engine writes about, by priority. Seasonal topics carry a publish window.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-topics".
 */
export interface AiTopic {
  id: number;
  title: string;
  /**
   * The language the post is written in: it lands on the Arabic or the English blog.
   */
  language: 'ar' | 'en';
  hub: number | Category;
  intent: 'informational' | 'commercial' | 'seasonal';
  priority: number;
  primaryKeyword: string;
  secondaryKeywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  windowStart?: string | null;
  /**
   * Seasonal topics publish inside the window only. Leave both empty for an evergreen topic.
   */
  windowEnd?: string | null;
  status: 'backlog' | 'scheduled' | 'generating' | 'published' | 'failed' | 'rejected';
  source: 'seed' | 'manual' | 'searchConsole';
  notes?: string | null;
  post?: (number | null) | Post;
  lastRun?: (number | null) | AiRun;
  lastError?: string | null;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Every run of the engine: its steps, score, estimated cost and the resulting post. Read-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-runs".
 */
export interface AiRun {
  id: number;
  label: string;
  kind: 'generate' | 'freshness';
  status: 'running' | 'done' | 'failed' | 'skipped';
  provider?: string | null;
  model?: string | null;
  score?: number | null;
  tokensIn?: number | null;
  tokensOut?: number | null;
  costUsd?: number | null;
  durationMs?: number | null;
  rubric?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  steps?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The freshness job regenerates from it.
   */
  outline?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  systemPromptVersion?: number | null;
  topic?: (number | null) | AiTopic;
  post?: (number | null) | Post;
  error?: string | null;
  startedAt?: string | null;
  finishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Send an old URL to a page or a new URL. Live as soon as it is saved.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
  };
  type: '301' | '302';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          'inline' | 'indexnow-ping' | 'content-tick' | 'content-freshness' | 'content-digest' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  workflowSlug?: 'generatePost' | null;
  taskSlug?:
    ('inline' | 'indexnow-ping' | 'content-tick' | 'content-freshness' | 'content-digest' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'integrations';
        value: number | Integration;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'ai-topics';
        value: number | AiTopic;
      } | null)
    | ({
        relationTo: 'ai-runs';
        value: number | AiRun;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  baseCost?: T;
  suggestedPrice?: T;
  sortOrder?: T;
  colors?:
    | T
    | {
        slug?: T;
        name?: T;
        hex?: T;
        front?: T;
        back?: T;
        id?: T;
      };
  sizes?:
    | T
    | {
        label?: T;
        length?: T;
        chest?: T;
        sleeve?: T;
        id?: T;
      };
  sizesSummary?: T;
  material?: T;
  weightGrams?: T;
  printArea?:
    | T
    | {
        label?: T;
        widthCm?: T;
        heightCm?: T;
        canvas?:
          | T
          | {
              x?: T;
              y?: T;
              w?: T;
              h?: T;
            };
      };
  printMethodLabel?: T;
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  lead?: T;
  blocks?:
    | T
    | {
        richText?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        story?:
          | T
          | {
              heading?: T;
              text?: T;
              line?: T;
              photo?: T;
              withFacts?: T;
              id?: T;
              blockName?: T;
            };
        cards?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    text?: T;
                    art?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        steps?:
          | T
          | {
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        profitEquation?:
          | T
          | {
              title?: T;
              sell?: T;
              base?: T;
              profit?: T;
              exampleLine?: T;
              id?: T;
              blockName?: T;
            };
        faqList?:
          | T
          | {
              selection?: T;
              offset?: T;
              limit?: T;
              title?: T;
              linkLabel?: T;
              linkHref?: T;
              bottomLine?: T;
              bottomLinkWord?: T;
              id?: T;
              blockName?: T;
            };
        miskCredential?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              whatsappTitle?: T;
              whatsappText?: T;
              emailTitle?: T;
              phoneTitle?: T;
              followTitle?: T;
              booking?:
                | T
                | {
                    title?: T;
                    text?: T;
                    button?: T;
                    whatsappMessage?: T;
                  };
              id?: T;
              blockName?: T;
            };
        legalBody?:
          | T
          | {
              updatedAt?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        mediaBanner?:
          | T
          | {
              media?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  group?: T;
  order?: T;
  showOnHome?: T;
  homeOrder?: T;
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  store?: T;
  avatar?: T;
  order?: T;
  placeholder?: T;
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations_select".
 */
export interface IntegrationsSelect<T extends boolean = true> {
  platform?: T;
  order?: T;
  name?: T;
  nameLatin?: T;
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  hub?: T;
  tags?: T;
  cover?: T;
  takeaways?:
    | T
    | {
        text?: T;
        id?: T;
      };
  body?: T;
  author?: T;
  publishedAt?: T;
  contentUpdatedAt?: T;
  readingMinutes?: T;
  origin?: T;
  factsBaseline?: T;
  warnings?:
    | T
    | {
        text?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  lead?: T;
  defaultCover?: T;
  order?: T;
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  bio?: T;
  photo?: T;
  sameAs?:
    | T
    | {
        url?: T;
        id?: T;
      };
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-topics_select".
 */
export interface AiTopicsSelect<T extends boolean = true> {
  title?: T;
  language?: T;
  hub?: T;
  intent?: T;
  priority?: T;
  primaryKeyword?: T;
  secondaryKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  windowStart?: T;
  windowEnd?: T;
  status?: T;
  source?: T;
  notes?: T;
  post?: T;
  lastRun?: T;
  lastError?: T;
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-runs_select".
 */
export interface AiRunsSelect<T extends boolean = true> {
  label?: T;
  kind?: T;
  status?: T;
  provider?: T;
  model?: T;
  score?: T;
  tokensIn?: T;
  tokensOut?: T;
  costUsd?: T;
  durationMs?: T;
  rubric?: T;
  steps?: T;
  outline?: T;
  systemPromptVersion?: T;
  topic?: T;
  post?: T;
  error?: T;
  startedAt?: T;
  finishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  workflowSlug?: T;
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The home page, section by section. Drafts are free; publishing is live within seconds.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero: {
    slides: {
      headline: string;
      subline: string;
      imageDesktop: number | Media;
      imageMobile: number | Media;
      id?: string | null;
    }[];
    primaryCta: string;
    secondaryCta: string;
    microcopy: string;
    chips: {
      text: string;
      id?: string | null;
    }[];
  };
  productStrip: {
    eyebrow: string;
    title: string;
    lead: string;
    pricePrefix: string;
    button: string;
    /**
     * Published products only; one unpublished later drops out of the strip until it is published again.
     */
    products: (number | Product)[];
  };
  designer: {
    eyebrow: string;
    title: string;
    lead: string;
    cta: string;
  };
  steps: {
    /**
     * Off hides the “Three steps” section from the home page.
     */
    enabled?: boolean | null;
    eyebrow: string;
    title: string;
    link: string;
    items: {
      title: string;
      text: string;
      icon: number | Media;
      id?: string | null;
    }[];
  };
  /**
   * The loop itself ships with the site; only the copy lives here.
   */
  video: {
    /**
     * Off hides the “Video” section from the home page.
     */
    enabled?: boolean | null;
    title: string;
    lead: string;
  };
  whyUs: {
    /**
     * Off hides the “Why us” section from the home page.
     */
    enabled?: boolean | null;
    eyebrow: string;
    title: string;
    items: {
      icon: 'ShieldCheck' | 'Workflow' | 'Zap';
      title: string;
      text: string;
      id?: string | null;
    }[];
  };
  /**
   * The entries live in Testimonials; the section title lives here.
   */
  testimonials: {
    /**
     * Off hides the “Testimonials” section from the home page.
     */
    enabled?: boolean | null;
    eyebrow: string;
    title: string;
  };
  integrations: {
    /**
     * Off hides the “Integrations” section from the home page.
     */
    enabled?: boolean | null;
    title: string;
    lead: string;
  };
  /**
   * The entries flagged «show on home» in the FAQ collection.
   */
  faq: {
    /**
     * Off hides the “FAQ” section from the home page.
     */
    enabled?: boolean | null;
    title: string;
    link: string;
  };
  ribbon: {
    title: string;
    lead: string;
    button: string;
  };
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site name, contact details, social accounts and the welcome offer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  brandName: string;
  brandNameLatin: string;
  tagline: string;
  contact: {
    phone: string;
    phoneIntl: string;
    whatsapp: string;
    email: string;
  };
  social: {
    x: string;
    instagram: string;
    tiktok: string;
  };
  /**
   * Must match the app; no automatic sync.
   */
  welcomeCredit: number;
  /**
   * Must match the app; no automatic sync.
   */
  deliveryMaxDays: number;
  deliveryOrigin: string;
  deliveryRegion: string;
  /**
   * Leave empty to use WhatsApp
   */
  bookingUrl?: string | null;
  appUrls: {
    register: string;
    login: string;
  };
  legalEntity: string;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Header and footer links and the button labels.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  primary: {
    label: string;
    href: string;
    /**
     * e.g. /products
     */
    matchPrefix?: string | null;
    id?: string | null;
  }[];
  policies: {
    label: string;
    href: string;
    /**
     * e.g. /products
     */
    matchPrefix?: string | null;
    id?: string | null;
  }[];
  ctaLabel: string;
  loginLabel: string;
  skipLinkLabel: string;
  menuOpenLabel: string;
  menuCloseLabel: string;
  menuWhatsappLine: string;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Search titles and descriptions for the fixed pages, and the default share image.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: number;
  /**
   * %s is the page title
   */
  titleTemplate: string;
  /**
   * Title and description per static route
   */
  routes: {
    route: string;
    /**
     * Used for the sitemap
     */
    updatedAt: string;
    title: string;
    /**
     * Aim for ≤ 155 characters
     */
    description: string;
    ogImage?: string | null;
    id?: string | null;
  }[];
  /**
   * Optional: env variables are used when empty.
   */
  verification?: {
    google?: string | null;
    bing?: string | null;
  };
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The engine publishes without a human step (D-44). Unreviewed high-volume AI publishing risks the scaled-content policy of Google: keep the cadence moderate and the quality gates strict.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-settings".
 */
export interface AiSetting {
  id: number;
  /**
   * The mock only runs when AI_CONTENT_MOCK=1 is set in the environment.
   */
  activeProvider: 'openai' | 'deepseek' | 'anthropic' | 'google' | 'mock';
  providers: {
    openai: {
      /**
       * As in the vendor docs.
       */
      model: string;
      /**
       * Stored encrypted and never shown again; leave the mask to keep it, clear it to remove it.
       */
      apiKey?: string | null;
      inputPerMillionUsd: number;
      outputPerMillionUsd: number;
    };
    deepseek: {
      /**
       * As in the vendor docs.
       */
      model: string;
      /**
       * Stored encrypted and never shown again; leave the mask to keep it, clear it to remove it.
       */
      apiKey?: string | null;
      inputPerMillionUsd: number;
      outputPerMillionUsd: number;
    };
    anthropic: {
      /**
       * As in the vendor docs.
       */
      model: string;
      /**
       * Stored encrypted and never shown again; leave the mask to keep it, clear it to remove it.
       */
      apiKey?: string | null;
      inputPerMillionUsd: number;
      outputPerMillionUsd: number;
    };
    google: {
      /**
       * As in the vendor docs.
       */
      model: string;
      /**
       * Stored encrypted and never shown again; leave the mask to keep it, clear it to remove it.
       */
      apiKey?: string | null;
      inputPerMillionUsd: number;
      outputPerMillionUsd: number;
    };
  };
  /**
   * The kill switch. Off, no new run starts within the hour.
   */
  enabled?: boolean | null;
  /**
   * The research-backed range: 8 to 16 posts a month; quality before quantity.
   */
  postsPerDay: number;
  publishHourRiyadh: number;
  maxPostsPerMonth: number;
  dailyCostCapUsd: number;
  /**
   * While above zero the posts of a live provider land as drafts for your read; set it to 0 once they read well.
   */
  reviewFirstRuns: number;
  style: {
    styleGuide: string;
    systemPrompt: string;
    systemPromptVersion?: number | null;
    bannedPhrases: string;
    bannedClaims: string;
  };
  images: {
    /**
     * Generation is refused until an image provider is wired; Pexels needs a key.
     */
    imageMode: 'hubDefault' | 'stock' | 'generate';
    imageStyle?: string | null;
    /**
     * Stored encrypted and never shown again; leave the mask to keep it, clear it to remove it.
     */
    pexelsKey?: string | null;
  };
  quality: {
    qualityThreshold: number;
    maxRevisionPasses: number;
    minWords: number;
    maxWords: number;
  };
  notifications?: {
    /**
     * Gets failure alerts and the weekly digest.
     */
    notifyEmail?: string | null;
    weeklyDigest?: boolean | null;
    failureAlerts?: boolean | null;
  };
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        slides?:
          | T
          | {
              headline?: T;
              subline?: T;
              imageDesktop?: T;
              imageMobile?: T;
              id?: T;
            };
        primaryCta?: T;
        secondaryCta?: T;
        microcopy?: T;
        chips?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  productStrip?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        pricePrefix?: T;
        button?: T;
        products?: T;
      };
  designer?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        cta?: T;
      };
  steps?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        link?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              icon?: T;
              id?: T;
            };
      };
  video?:
    | T
    | {
        enabled?: T;
        title?: T;
        lead?: T;
      };
  whyUs?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  testimonials?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
      };
  integrations?:
    | T
    | {
        enabled?: T;
        title?: T;
        lead?: T;
      };
  faq?:
    | T
    | {
        enabled?: T;
        title?: T;
        link?: T;
      };
  ribbon?:
    | T
    | {
        title?: T;
        lead?: T;
        button?: T;
      };
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  brandNameLatin?: T;
  tagline?: T;
  contact?:
    | T
    | {
        phone?: T;
        phoneIntl?: T;
        whatsapp?: T;
        email?: T;
      };
  social?:
    | T
    | {
        x?: T;
        instagram?: T;
        tiktok?: T;
      };
  welcomeCredit?: T;
  deliveryMaxDays?: T;
  deliveryOrigin?: T;
  deliveryRegion?: T;
  bookingUrl?: T;
  appUrls?:
    | T
    | {
        register?: T;
        login?: T;
      };
  legalEntity?: T;
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  primary?:
    | T
    | {
        label?: T;
        href?: T;
        matchPrefix?: T;
        id?: T;
      };
  policies?:
    | T
    | {
        label?: T;
        href?: T;
        matchPrefix?: T;
        id?: T;
      };
  ctaLabel?: T;
  loginLabel?: T;
  skipLinkLabel?: T;
  menuOpenLabel?: T;
  menuCloseLabel?: T;
  menuWhatsappLine?: T;
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  titleTemplate?: T;
  routes?:
    | T
    | {
        route?: T;
        updatedAt?: T;
        title?: T;
        description?: T;
        ogImage?: T;
        id?: T;
      };
  verification?:
    | T
    | {
        google?: T;
        bing?: T;
      };
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-settings_select".
 */
export interface AiSettingsSelect<T extends boolean = true> {
  activeProvider?: T;
  providers?:
    | T
    | {
        openai?:
          | T
          | {
              model?: T;
              apiKey?: T;
              inputPerMillionUsd?: T;
              outputPerMillionUsd?: T;
            };
        deepseek?:
          | T
          | {
              model?: T;
              apiKey?: T;
              inputPerMillionUsd?: T;
              outputPerMillionUsd?: T;
            };
        anthropic?:
          | T
          | {
              model?: T;
              apiKey?: T;
              inputPerMillionUsd?: T;
              outputPerMillionUsd?: T;
            };
        google?:
          | T
          | {
              model?: T;
              apiKey?: T;
              inputPerMillionUsd?: T;
              outputPerMillionUsd?: T;
            };
      };
  enabled?: T;
  postsPerDay?: T;
  publishHourRiyadh?: T;
  maxPostsPerMonth?: T;
  dailyCostCapUsd?: T;
  reviewFirstRuns?: T;
  style?:
    | T
    | {
        styleGuide?: T;
        systemPrompt?: T;
        systemPromptVersion?: T;
        bannedPhrases?: T;
        bannedClaims?: T;
      };
  images?:
    | T
    | {
        imageMode?: T;
        imageStyle?: T;
        pexelsKey?: T;
      };
  quality?:
    | T
    | {
        qualityThreshold?: T;
        maxRevisionPasses?: T;
        minWords?: T;
        maxWords?: T;
      };
  notifications?:
    | T
    | {
        notifyEmail?: T;
        weeklyDigest?: T;
        failureAlerts?: T;
      };
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskIndexnow-ping".
 */
export interface TaskIndexnowPing {
  input: {
    urls:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output: {
    status?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskContent-tick".
 */
export interface TaskContentTick {
  input?: unknown;
  output: {
    queued?: boolean | null;
    reason?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskContent-freshness".
 */
export interface TaskContentFreshness {
  input?: unknown;
  output: {
    checked?: number | null;
    queued?: number | null;
    reason?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskContent-digest".
 */
export interface TaskContentDigest {
  input?: unknown;
  output: {
    sent?: boolean | null;
    deleted?: number | null;
    reason?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'products';
          value: number | Product;
        } | null)
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'testimonials';
          value: number | Testimonial;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: 'home' | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowGeneratePost".
 */
export interface WorkflowGeneratePost {
  input: {
    topicId?: number | null;
    manual?: boolean | null;
    replacePostId?: number | null;
    kind?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}