/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    pages: Page;
    faqs: Faq;
    testimonials: Testimonial;
    integrations: Integration;
    posts: Post;
    categories: Category;
    authors: Author;
    tags: Tag;
    'ai-topics': AiTopic;
    'ai-runs': AiRun;
    connections: Connection;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    integrations: IntegrationsSelect<false> | IntegrationsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'ai-topics': AiTopicsSelect<false> | AiTopicsSelect<true>;
    'ai-runs': AiRunsSelect<false> | AiRunsSelect<true>;
    connections: ConnectionsSelect<false> | ConnectionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ar' | 'en') | ('ar' | 'en')[];
  globals: {
    home: Home;
    'site-settings': SiteSetting;
    'seo-defaults': SeoDefault;
    'ai-settings': AiSetting;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'seo-defaults': SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
    'ai-settings': AiSettingsSelect<false> | AiSettingsSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: 'ar' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'indexnow-ping': TaskIndexnowPing;
      'content-tick': TaskContentTick;
      'content-freshness': TaskContentFreshness;
      'content-digest': TaskContentDigest;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: {
      generatePost: WorkflowGeneratePost;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Panel accounts. Editors change content; admins also change settings and users.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * The name as it shows in "Last saved" on documents and in the account menu. Not shown on the site.
   */
  name: string;
  /**
   * Admin: opens settings, users and the engine. Editor: changes content only. Not shown on the site.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Images and files used by pages and products. Give every image alt text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image in the language of the open locale tab; required.
   */
  alt: string;
  /**
   * The photo's source or photographer, for the record. Not shown on the site.
   */
  credit?: string | null;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Products on the site and in the designer: prices, photos, sizes and colours.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * The product's name on its card, its page title, the designer's picker and llms.txt.
   */
  name: string;
  /**
   * The last part of the page address: b7r.sa/products/tee-essential. Lowercase letters and hyphens only; changing it after publishing breaks old links.
   */
  slug: string;
  /**
   * One line under the name on the product card, the description of the product page's Google result, and the product's line in llms.txt.
   */
  shortDescription: string;
  /**
   * The paragraph at the top of the product's page, under the name.
   */
  description: string;
  /**
   * What the merchant pays per piece: the product page, the calculator, the home strip and llms.txt. Must equal the app's price: there is no sync.
   */
  baseCost: number;
  /**
   * The sell price we suggest to the merchant: the product page, the calculator and llms.txt. Must equal the app's: there is no sync.
   */
  suggestedPrice: number;
  /**
   * Where the product sits on the products page and in llms.txt: 1 shows first. The home strip has its own order (Home page, Product strip tab).
   */
  sortOrder: number;
  /**
   * The product's colours: the swatches on the card, the colour choice on the page and in the designer. The first is the default.
   */
  colors: {
    /**
     * The colour's id, used by the card's swatches and the designer: black, white. Lowercase; never shown to a visitor.
     */
    slug: string;
    /**
     * The colour name a visitor reads when choosing it on the page and in the designer.
     */
    name: string;
    /**
     * The colour of the small swatch: #000000. As close to the real fabric as possible.
     */
    hex: string;
    /**
     * The front photo in this colour: the card, the page, and the designer lays the design over it. Square, 1000 by 1000.
     */
    front: number | Media;
    /**
     * The back photo in this colour: the «back» toggle of the page's gallery. Leave empty if there is none.
     */
    back?: (number | null) | Media;
    id?: string | null;
  }[];
  /**
   * The sizes on offer: the size table on the product's page, in this order.
   */
  sizes: {
    /**
     * The size name in the product page's size table: S, M, One size.
     */
    label: string;
    /**
     * The piece's length in centimetres in the size table. Empty on every size hides the column.
     */
    length?: number | null;
    /**
     * The chest width in centimetres in the size table. Empty on every size hides the column.
     */
    chest?: number | null;
    /**
     * The sleeve length in centimetres in the size table. Empty on every size hides the column.
     */
    sleeve?: number | null;
    id?: string | null;
  }[];
  /**
   * Shows on the product card under the price. Short: "S – 2XL", "One size".
   */
  sizesSummary: string;
  /**
   * The material in the product page's facts line: 100% cotton, canvas.
   */
  material: string;
  /**
   * The weight in grams in the facts line; merchants ask for it before ordering.
   */
  weightGrams: number;
  /**
   * The print area: what a visitor reads on the page, and where the designer places the design on the photo.
   */
  printArea: {
    /**
     * The area as the page states it: "Front, 28 by 38 cm".
     */
    label: string;
    widthCm: number;
    heightCm: number;
    /**
     * Where the print area sits over the product photo in the designer.
     */
    canvas: {
      /**
       * Where the area starts from the left of the front photo, as a fraction of its width (0 to 1). Moves the design in the designer.
       */
      x: number;
      /**
       * Where the area starts from the top of the front photo, as a fraction of its height (0 to 1).
       */
      y: number;
      /**
       * The area's width as a fraction of the photo's width (0 to 1): the widest a design can be in the designer.
       */
      w: number;
      /**
       * The area's height as a fraction of the photo's height (0 to 1): the tallest a design can be in the designer.
       */
      h: number;
    };
  };
  /**
   * The print method in the product page's facts line: high-quality digital print.
   */
  printMethodLabel: string;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Site pages as editable blocks. The seven designed pages keep their URLs; add new ones freely.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * The page's title: the H1 at the top, and the tab name when no search title is set.
   */
  title: string;
  /**
   * The last part of the page address: b7r.sa/about. Lowercase letters and hyphens; changing it after publishing breaks old links.
   */
  slug: string;
  /**
   * One line under the title, in a lighter weight. Empty hides the line.
   */
  lead?: string | null;
  /**
   * The page's sections, top to bottom; drag to reorder. Each type has its own fields.
   */
  blocks: (
    | {
        /**
         * The section's heading (H2) above the text. Empty shows the text alone.
         */
        title?: string | null;
        /**
         * The formatted text itself: paragraphs, subheadings, lists, links.
         */
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'richText';
      }
    | {
        /**
         * The heading of the story section on the About page, above the photo and the text.
         */
        heading: string;
        /**
         * The story beside the photo: one or two paragraphs.
         */
        text: string;
        /**
         * The location line under the text: "Jeddah, Saudi Arabia".
         */
        line: string;
        /**
         * The story photo beside the text, portrait 4:5.
         */
        photo: number | Media;
        /**
         * The welcome credit and the why-us pairs from the home page
         */
        withFacts?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'story';
      }
    | {
        /**
         * A heading above the card grid. Empty shows the cards alone.
         */
        title?: string | null;
        /**
         * The cards in grid order: an icon, a title, a text. Three per row on a desktop.
         */
        items: {
          /**
           * The icon at the card's top, from the fixed set.
           */
          icon: 'ShieldCheck' | 'Workflow' | 'Zap' | 'Target' | 'Eye' | 'Heart';
          /**
           * The card's title under the icon; two to four words.
           */
          title: string;
          /**
           * The card's text under the title: one or two sentences.
           */
          text: string;
          /**
           * A picture in place of the icon at the top of the card. Empty shows the icon.
           */
          art?: (number | null) | Media;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'cards';
      }
    | {
        /**
         * The numbered steps on the how-it-works page, in order: a 3D icon, a title, a text.
         */
        items: {
          /**
           * The step's title beside its number.
           */
          title: string;
          /**
           * The step's explanation under its title: one or two sentences.
           */
          text: string;
          /**
           * The step's 3D icon, from the library (icons-3d-*).
           */
          icon: number | Media;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'steps';
      }
    | {
        /**
         * The heading of the profit-equation band on the how-it-works page.
         */
        title: string;
        /**
         * The name of the first term of the equation: "Sell price".
         */
        sell: string;
        /**
         * The name of the second term: "Base cost".
         */
        base: string;
        /**
         * The name of the result, after the equals sign: "Your profit".
         */
        profit: string;
        /**
         * The worked example under the equation, with real catalogue numbers: "A tee at 89 SAR…".
         */
        exampleLine: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'profitEquation';
      }
    | {
        /**
         * Which entries show: all of them, grouped (the FAQ page), or the home entries only.
         */
        selection: 'all' | 'home';
        /**
         * How many entries to skip from the start. Empty or 0: none.
         */
        offset?: number | null;
        /**
         * The most entries shown. Empty: all of them.
         */
        limit?: number | null;
        /**
         * A heading above the list. Empty shows the list alone.
         */
        title?: string | null;
        /**
         * The text of a link under the list, such as "All questions". Empty hides the link.
         */
        linkLabel?: string | null;
        /**
         * Where the link under the list goes: /faq.
         */
        linkHref?: string | null;
        /**
         * A closing sentence under the list with one word carrying a link. Empty hides the sentence.
         */
        bottomLine?: string | null;
        /**
         * The word of the closing sentence that becomes the link; it must appear in the sentence exactly.
         */
        bottomLinkWord?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faqList';
      }
    | {
        /**
         * The title of the Misk Launchpad card on the About page.
         */
        title: string;
        /**
         * The card's text under the title: what the programme is and what it means for B7R.
         */
        text: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'miskCredential';
      }
    | {
        /**
         * The title of the WhatsApp card on the contact page.
         */
        whatsappTitle: string;
        /**
         * The line under the WhatsApp card's title: when we answer.
         */
        whatsappText: string;
        /**
         * The title of the e-mail card on the contact page; the address itself comes from Site settings.
         */
        emailTitle: string;
        /**
         * The title of the phone card; the number itself comes from Site settings.
         */
        phoneTitle: string;
        /**
         * The title of the social card; the links come from Site settings.
         */
        followTitle: string;
        /**
         * The consultation card: opens the booking link from Site settings, or WhatsApp with a prefilled message when it is empty.
         */
        booking: {
          /**
           * The booking card's title on the contact page.
           */
          title: string;
          /**
           * The line under the booking card's title: the length and that it is free.
           */
          text: string;
          /**
           * The booking button's text on the card.
           */
          button: string;
          /**
           * The prefilled message WhatsApp opens with when there is no booking link.
           */
          whatsappMessage: string;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'contact';
      }
    | {
        /**
         * The "last updated" date at the top of the legal page, and the modified date search engines read.
         */
        updatedAt: string;
        /**
         * ## headings become the on-this-page list; no HTML.
         */
        body: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'legalBody';
      }
    | {
        /**
         * The section's wide image, the full width of the page.
         */
        media: number | Media;
        /**
         * A line under the image. Empty hides it.
         */
        caption?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'mediaBanner';
      }
  )[];
  /**
   * What search engines and shares see: the title and description in the Google result, the image when the link is shared.
   */
  seo: {
    /**
     * The search result's title and the browser tab; the site name from Search defaults is appended. Up to 70 characters.
     */
    title: string;
    /**
     * The description under the title in the search result. One or two sentences, up to 160 characters.
     */
    description: string;
    /**
     * The image shown when the link is shared on WhatsApp and X. Empty uses the site's default.
     */
    ogImage?: (number | null) | Media;
  };
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * FAQ entries by group. Up to five show on the home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  /**
   * The question as it reads on the FAQ page, and in the home page section when flagged for it.
   */
  question: string;
  /**
   * The answer under the question on the FAQ page and in the home section: plain text, no links, two to four sentences.
   */
  answer: string;
  /**
   * The group the question is listed under on the FAQ page; the group headings are fixed.
   */
  group: 'البداية' | 'الأسعار والربح' | 'الطلبات والتوصيل' | 'المتاجر والربط' | 'الجودة والدعم';
  /**
   * Where the question sits inside its group on the FAQ page: 1 first.
   */
  order: number;
  /**
   * On: the entry also shows in the home FAQ section (five at most, sorted by "Order on the home page").
   */
  showOnHome?: boolean | null;
  /**
   * Where the question sits in the home page section, for entries flagged «show on home»: 1 first.
   */
  homeOrder?: number | null;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Merchant quotes on the home page. Placeholders never show on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * The merchant's words as they read on the card on the home page. Two or three sentences, no numbers that cannot be proven.
   */
  quote: string;
  /**
   * The merchant's name under the quote on the home page.
   */
  name: string;
  /**
   * The merchant's store name under their name on the card.
   */
  store: string;
  /**
   * Read by nothing on the site today: the card shows the name and the store, no photo. Kept for the day the cards carry photos.
   */
  avatar?: (number | null) | Media;
  /**
   * Where the card sits in the home page section: 1 first.
   */
  order: number;
  /**
   * Placeholders show a «sample» badge on previews and are omitted on b7r.sa until a real entry exists.
   */
  placeholder?: boolean | null;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Connected platforms (Salla, Zid, Shopify) and their order in the integrations strip.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations".
 */
export interface Integration {
  id: number;
  /**
   * Which platform this is: picks the logo shown in the connected-stores section; the name fields say how it is written.
   */
  platform: 'salla' | 'zid' | 'shopify';
  /**
   * Where the platform's logo sits in the home page section: 1 first.
   */
  order: number;
  /**
   * The platform's name as a visitor reads it under its logo: Salla, Zid.
   */
  name: string;
  /**
   * The platform's Latin name: structured data and the logo's alt text. Salla, Zid, Shopify.
   */
  nameLatin: string;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog posts. Drafts stay private; publishing needs a cover, three takeaways and two internal links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * The post's title: the H1 on its page, its name on the blog cards, in the feed and llms.txt. Up to 70 characters.
   */
  title: string;
  /**
   * The last part of the post address: b7r.sa/blog/how-to-price. Lowercase letters and hyphens; changing it after publishing breaks old links.
   */
  slug: string;
  /**
   * H2s as questions, short paragraphs, at least two links to pages of this site.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * One or two sentences on the post card and in search results.
   */
  excerpt: string;
  /**
   * The hub the post belongs to: the hub's page lists it, and the hub line shows above the title.
   */
  hub: number | Category;
  /**
   * Tags for sorting posts inside the admin (the list filters by them). Not shown on the site; related posts are chosen by hub.
   */
  tags?: (number | Tag)[] | null;
  /**
   * The cover with its Arabic alt text in the library.
   */
  cover: number | Media;
  /**
   * The "key takeaways" box above the body: three short sentences for the reader in a hurry and for answer engines.
   */
  takeaways: {
    /**
     * One takeaway: a full sentence, no full stop at the end.
     */
    text: string;
    id?: string | null;
  }[];
  /**
   * Optional: the title and the excerpt are used when left empty.
   */
  seo?: {
    /**
     * The search result's title and the browser tab. Empty uses the post's title. Up to 70 characters.
     */
    title?: string | null;
    /**
     * The description under the title in the search result. Empty uses the excerpt. Up to 160 characters.
     */
    description?: string | null;
    /**
     * The image shown when the link is shared on WhatsApp and X. Empty uses the cover.
     */
    ogImage?: (number | null) | Media;
  };
  /**
   * The author in the byline under the title and in the search data; opens the author's page.
   */
  author: number | Author;
  /**
   * Filled on the first publish when left empty.
   */
  publishedAt?: string | null;
  /**
   * Shown on the post when its content really changed.
   */
  contentUpdatedAt?: string | null;
  readingMinutes?: number | null;
  /**
   * A change by an editor to an engine post marks it "engine, then edited" and exempts it from the freshness job.
   */
  origin: 'manual' | 'ai' | 'ai-edited';
  factsBaseline?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  warnings?:
    | {
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The six blog hubs. Each has its own page, description and default cover.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * The hub's name: its page title on the blog, and the hub line above each post's title.
   */
  name: string;
  /**
   * The last part of the hub page address: b7r.sa/blog/category/pricing. Lowercase letters and hyphens.
   */
  slug: string;
  /**
   * One sentence under the hub title and on the blog cards.
   */
  description: string;
  /**
   * A line under the hub's name on its page. Empty hides the line.
   */
  lead?: string | null;
  /**
   * Used when a post has no cover of its own.
   */
  defaultCover?: (number | null) | Media;
  /**
   * Where the hub sits in the blog's hub list: 1 first.
   */
  order: number;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Optional tags that connect related posts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * The tag's name in the posts list and its filters inside the admin. Not shown on the site.
   */
  name: string;
  /**
   * The tag's id: lowercase letters and hyphens. Not shown on the site.
   */
  slug: string;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Who signs the blog posts. Each author has a page on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  /**
   * The author's name in the byline under a post's title and on their page.
   */
  name: string;
  /**
   * The last part of the author page address: b7r.sa/author/dhia. Lowercase letters and hyphens.
   */
  slug: string;
  /**
   * The role under the author name in the byline and on their page: "Founder of B7R Print".
   */
  role: string;
  /**
   * The author's bio on their page and in the search data. Two or three sentences. Empty hides the paragraph.
   */
  bio?: string | null;
  /**
   * The author's round photo on their page and beside the byline. Empty shows the initial.
   */
  photo?: (number | null) | Media;
  /**
   * Public profiles (X, LinkedIn…) for the structured data of the page.
   */
  sameAs?:
    | {
        /**
         * An official profile of the author (LinkedIn, X): ties the name to the person in the search data. Not shown to a visitor.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * What the engine writes about, by priority. Seasonal topics carry a publish window.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-topics".
 */
export interface AiTopic {
  id: number;
  /**
   * The working title of the topic; the engine writes the final title itself. Not shown on the site.
   */
  title: string;
  /**
   * The language the post is written in: it lands on the Arabic or the English blog.
   */
  language: 'ar' | 'en';
  /**
   * The hub the post is filed under when it is written.
   */
  hub: number | Category;
  /**
   * Who the post is for: informational (learning), commercial (comparing to buy), seasonal (an occasion with a date).
   */
  intent: 'informational' | 'commercial' | 'seasonal';
  /**
   * Priority 1 (highest) to 5; the engine takes the highest priority in the backlog first.
   */
  priority: number;
  /**
   * The phrase people search for that the post must target: "pricing a printed t-shirt".
   */
  primaryKeyword: string;
  /**
   * Secondary search phrases the post works in where they fit.
   */
  secondaryKeywords?:
    | {
        /**
         * One phrase as a searcher types it.
         */
        keyword: string;
        id?: string | null;
      }[]
    | null;
  /**
   * For seasonal topics: the date after which the engine may write it (about six weeks before the occasion).
   */
  windowStart?: string | null;
  /**
   * Seasonal topics publish inside the window only. Leave both empty for an evergreen topic.
   */
  windowEnd?: string | null;
  /**
   * Where the topic is in the cycle: backlog, scheduled, generating, published, failed, rejected.
   */
  status: 'backlog' | 'scheduled' | 'generating' | 'published' | 'failed' | 'rejected';
  /**
   * Where the topic came from: the seed list, added by hand, or Search Console.
   */
  source: 'seed' | 'manual' | 'searchConsole';
  /**
   * Notes for the engine before it writes: an angle, an example, what to avoid. Not shown on the site.
   */
  notes?: string | null;
  post?: (number | null) | Post;
  lastRun?: (number | null) | AiRun;
  lastError?: string | null;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Every run of the engine: its steps, score, estimated cost and the resulting post. Read-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-runs".
 */
export interface AiRun {
  id: number;
  label: string;
  kind: 'generate' | 'freshness';
  status: 'running' | 'done' | 'failed' | 'skipped';
  provider?: string | null;
  model?: string | null;
  score?: number | null;
  tokensIn?: number | null;
  tokensOut?: number | null;
  costUsd?: number | null;
  durationMs?: number | null;
  rubric?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  steps?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * The freshness job regenerates from it.
   */
  outline?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  systemPromptVersion?: number | null;
  connection?: (number | null) | Connection;
  topic?: (number | null) | AiTopic;
  post?: (number | null) | Post;
  error?: string | null;
  startedAt?: string | null;
  finishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The AI accounts: one key per service, a test, and a monthly spending limit. The engine writes with the connection picked in its settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connections".
 */
export interface Connection {
  id: number;
  /**
   * A name you recognise in the list and in the engine settings: "OpenAI, production". Never shown to a visitor.
   */
  label: string;
  /**
   * The service the key is sent to. "OpenAI-compatible endpoint" fits any other AI that serves the OpenAI API at its own address; "Mock" is for tests only.
   */
  kind: 'openai' | 'anthropic' | 'google' | 'deepseek' | 'openai-compatible' | 'mock';
  /**
   * The model id exactly as the service docs write it: gpt-4.1, claude-sonnet-4-5, gemini-2.5-pro, deepseek-chat. Empty on save: the usual model of the service.
   */
  model?: string | null;
  /**
   * The compatible service’s address, https:// and without the chat path: https://api.example.com/v1.
   */
  baseUrl?: string | null;
  /**
   * Stored encrypted and never shown again; leave the mask to keep it, clear it to remove it.
   */
  apiKey?: string | null;
  /**
   * The service's price per million input tokens in USD, from its pricing page; each run's cost estimate and the monthly limit follow from it. Empty on save: the service's published price.
   */
  inputPerMillionUsd?: number | null;
  /**
   * The service's price per million output tokens in USD, from its pricing page; each run's cost estimate and the monthly limit follow from it. Empty on save: the service's published price.
   */
  outputPerMillionUsd?: number | null;
  /**
   * The most this connection may cost in a month (from the 1st, Riyadh time), estimated; past it the engine refuses to run on it until next month. Empty: no limit. The daily cap lives in the engine settings.
   */
  monthlyLimitUsd?: number | null;
  /**
   * Off refuses every engine run on this connection and says so on the dashboard; Test still works.
   */
  enabled?: boolean | null;
  /**
   * The estimated cost of this connection's runs since the 1st (Riyadh), from the runs log. A Test never counts.
   */
  spentThisMonthUsd?: number | null;
  /**
   * How many engine runs this connection served since the 1st (Riyadh), from the runs log.
   */
  callsThisMonth?: number | null;
  lastTestAt?: string | null;
  lastTestOk?: boolean | null;
  /**
   * What the service said at the last test: the model id on success, its error on failure.
   */
  lastTestMessage?: string | null;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Send an old URL to a page or a new URL. Live as soon as it is saved.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    url?: string | null;
  };
  type: '301' | '302';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          'inline' | 'indexnow-ping' | 'content-tick' | 'content-freshness' | 'content-digest' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  workflowSlug?: 'generatePost' | null;
  taskSlug?:
    ('inline' | 'indexnow-ping' | 'content-tick' | 'content-freshness' | 'content-digest' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'integrations';
        value: number | Integration;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'ai-topics';
        value: number | AiTopic;
      } | null)
    | ({
        relationTo: 'ai-runs';
        value: number | AiRun;
      } | null)
    | ({
        relationTo: 'connections';
        value: number | Connection;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  baseCost?: T;
  suggestedPrice?: T;
  sortOrder?: T;
  colors?:
    | T
    | {
        slug?: T;
        name?: T;
        hex?: T;
        front?: T;
        back?: T;
        id?: T;
      };
  sizes?:
    | T
    | {
        label?: T;
        length?: T;
        chest?: T;
        sleeve?: T;
        id?: T;
      };
  sizesSummary?: T;
  material?: T;
  weightGrams?: T;
  printArea?:
    | T
    | {
        label?: T;
        widthCm?: T;
        heightCm?: T;
        canvas?:
          | T
          | {
              x?: T;
              y?: T;
              w?: T;
              h?: T;
            };
      };
  printMethodLabel?: T;
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  lead?: T;
  blocks?:
    | T
    | {
        richText?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        story?:
          | T
          | {
              heading?: T;
              text?: T;
              line?: T;
              photo?: T;
              withFacts?: T;
              id?: T;
              blockName?: T;
            };
        cards?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    text?: T;
                    art?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        steps?:
          | T
          | {
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        profitEquation?:
          | T
          | {
              title?: T;
              sell?: T;
              base?: T;
              profit?: T;
              exampleLine?: T;
              id?: T;
              blockName?: T;
            };
        faqList?:
          | T
          | {
              selection?: T;
              offset?: T;
              limit?: T;
              title?: T;
              linkLabel?: T;
              linkHref?: T;
              bottomLine?: T;
              bottomLinkWord?: T;
              id?: T;
              blockName?: T;
            };
        miskCredential?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
              blockName?: T;
            };
        contact?:
          | T
          | {
              whatsappTitle?: T;
              whatsappText?: T;
              emailTitle?: T;
              phoneTitle?: T;
              followTitle?: T;
              booking?:
                | T
                | {
                    title?: T;
                    text?: T;
                    button?: T;
                    whatsappMessage?: T;
                  };
              id?: T;
              blockName?: T;
            };
        legalBody?:
          | T
          | {
              updatedAt?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        mediaBanner?:
          | T
          | {
              media?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  group?: T;
  order?: T;
  showOnHome?: T;
  homeOrder?: T;
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  store?: T;
  avatar?: T;
  order?: T;
  placeholder?: T;
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "integrations_select".
 */
export interface IntegrationsSelect<T extends boolean = true> {
  platform?: T;
  order?: T;
  name?: T;
  nameLatin?: T;
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  excerpt?: T;
  hub?: T;
  tags?: T;
  cover?: T;
  takeaways?:
    | T
    | {
        text?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  author?: T;
  publishedAt?: T;
  contentUpdatedAt?: T;
  readingMinutes?: T;
  origin?: T;
  factsBaseline?: T;
  warnings?:
    | T
    | {
        text?: T;
        id?: T;
      };
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  lead?: T;
  defaultCover?: T;
  order?: T;
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  role?: T;
  bio?: T;
  photo?: T;
  sameAs?:
    | T
    | {
        url?: T;
        id?: T;
      };
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-topics_select".
 */
export interface AiTopicsSelect<T extends boolean = true> {
  title?: T;
  language?: T;
  hub?: T;
  intent?: T;
  priority?: T;
  primaryKeyword?: T;
  secondaryKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  windowStart?: T;
  windowEnd?: T;
  status?: T;
  source?: T;
  notes?: T;
  post?: T;
  lastRun?: T;
  lastError?: T;
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-runs_select".
 */
export interface AiRunsSelect<T extends boolean = true> {
  label?: T;
  kind?: T;
  status?: T;
  provider?: T;
  model?: T;
  score?: T;
  tokensIn?: T;
  tokensOut?: T;
  costUsd?: T;
  durationMs?: T;
  rubric?: T;
  steps?: T;
  outline?: T;
  systemPromptVersion?: T;
  connection?: T;
  topic?: T;
  post?: T;
  error?: T;
  startedAt?: T;
  finishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connections_select".
 */
export interface ConnectionsSelect<T extends boolean = true> {
  label?: T;
  kind?: T;
  model?: T;
  baseUrl?: T;
  apiKey?: T;
  inputPerMillionUsd?: T;
  outputPerMillionUsd?: T;
  monthlyLimitUsd?: T;
  enabled?: T;
  spentThisMonthUsd?: T;
  callsThisMonth?: T;
  lastTestAt?: T;
  lastTestOk?: T;
  lastTestMessage?: T;
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  workflowSlug?: T;
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The home page, section by section. Drafts are free; publishing is live within seconds.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  hero: {
    /**
     * The four slides at the top of the home page, rotating; the first is what a visitor sees first. Each has a headline, a subline and two photos per language.
     */
    slides: {
      /**
       * The big headline on the slide, and the page's H1 for the first one. Two rows on a desktop: up to 6 words.
       */
      headline: string;
      /**
       * The line under the headline on the slide. One row on a desktop: up to 10 words.
       */
      subline: string;
      /**
       * Per language (the English site has no fallback). English: the mirrored composition, calm area under the copy.
       */
      imageDesktop: number | Media;
      /**
       * Per language (the English site has no fallback). English: the mirrored composition, calm area under the copy.
       */
      imageMobile: number | Media;
      id?: string | null;
    }[];
    /**
     * A one-colour fade from the copy side over the photo, so the headline reads on any photo.
     */
    overlay: {
      /**
       * Off shows the photo as it is behind the copy, with no fade.
       */
      enabled?: boolean | null;
      /**
       * The fade colour; white is the default. Written as #rrggbb.
       */
      color: string;
    };
    /**
     * The blue button under the slides; opens the app's sign-up.
     */
    primaryCta: string;
    /**
     * The link beside the button; opens the products page.
     */
    secondaryCta: string;
    /**
     * The welcome-credit line in the facts band of the About page (built from the home page).
     */
    microcopy: string;
    /**
     * Zero to 6; none hides the row. The rows are shared by both languages, the text is per language: a row without an English text does not show on the English site.
     */
    chips?:
      | {
          /**
           * The small chip under the buttons: "Kingdom-wide delivery in 5 days". Two to five words.
           */
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  productStrip: {
    /**
     * The small word above the product strip's title.
     */
    eyebrow: string;
    /**
     * The product strip's heading (H2).
     */
    title: string;
    /**
     * The line under the strip's heading.
     */
    lead: string;
    /**
     * The word before the price: the strip cards, the products page cards, and the product page with its sticky bar: "from". The price itself comes from the product.
     */
    pricePrefix: string;
    /**
     * The "all products" button under the strip; opens the products page.
     */
    button: string;
    /**
     * Published products only; one unpublished later drops out of the strip until it is published again.
     */
    products: (number | Product)[];
  };
  designer: {
    /**
     * The small word above the designer section's title.
     */
    eyebrow: string;
    /**
     * The designer section's heading (H2).
     */
    title: string;
    /**
     * The line under the designer's heading: what a visitor does here.
     */
    lead: string;
    /**
     * The button at the end of the designer; opens the app's sign-up.
     */
    cta: string;
  };
  steps: {
    /**
     * Off hides the “Three steps” section from the home page.
     */
    enabled?: boolean | null;
    /**
     * The small word above the three steps' title.
     */
    eyebrow: string;
    /**
     * The three steps' heading (H2).
     */
    title: string;
    /**
     * The "learn more" link under the steps; opens the how-it-works page.
     */
    link: string;
    /**
     * The three steps in order: a 3D icon, a title, a text.
     */
    items: {
      /**
       * The step's title beside its number; two to four words.
       */
      title: string;
      /**
       * The step's explanation under the title: one sentence.
       */
      text: string;
      /**
       * The step's 3D icon, from the library (icons-3d-*).
       */
      icon: number | Media;
      id?: string | null;
    }[];
  };
  video: {
    /**
     * Off hides the “Video” section from the home page.
     */
    enabled?: boolean | null;
    /**
     * The heading above the video; the loop itself ships with the site.
     */
    title: string;
    /**
     * The line under the video's heading.
     */
    lead: string;
  };
  whyUs: {
    /**
     * Off hides the “Why us” section from the home page.
     */
    enabled?: boolean | null;
    /**
     * The small word above the "why us" title.
     */
    eyebrow: string;
    /**
     * The "why us" heading (H2).
     */
    title: string;
    /**
     * The three cards in order: an icon, a title, a text. Also the facts band of the About page.
     */
    items: {
      /**
       * The card's icon, from the fixed set.
       */
      icon: 'ShieldCheck' | 'Workflow' | 'Zap';
      /**
       * The card's title; two to four words.
       */
      title: string;
      /**
       * The card's text: one sentence with a number or a promise that can be kept.
       */
      text: string;
      id?: string | null;
    }[];
  };
  testimonials: {
    /**
     * Off hides the “Testimonials” section from the home page.
     */
    enabled?: boolean | null;
    /**
     * The small word above the testimonials' title.
     */
    eyebrow: string;
    /**
     * The testimonials heading (H2); the quotes come from the Testimonials collection.
     */
    title: string;
  };
  integrations: {
    /**
     * Off hides the “Integrations” section from the home page.
     */
    enabled?: boolean | null;
    /**
     * The connected-stores heading (H2); the logos come from Store integrations.
     */
    title: string;
    /**
     * The line under the connected-stores heading.
     */
    lead: string;
  };
  faq: {
    /**
     * Off hides the “FAQ” section from the home page.
     */
    enabled?: boolean | null;
    /**
     * The home FAQ heading (H2); the entries come from the FAQ flagged «show on home».
     */
    title: string;
    /**
     * The "all questions" link under the section; opens the FAQ page.
     */
    link: string;
  };
  ribbon: {
    /**
     * The CTA ribbon heading at the bottom of every page, above the footer.
     */
    title: string;
    /**
     * The line under the ribbon's heading.
     */
    lead: string;
    /**
     * The ribbon's button; opens the app's sign-up.
     */
    button: string;
  };
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Site name, contact details, social accounts, the menus and the welcome offer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * The brand's name: the logo's accessible name in the header and the footer, the site name on share cards, the first line of llms.txt, the web app manifest, and the organisation data search engines read.
   */
  brandName: string;
  /**
   * The brand's Latin name: the alternate name in the organisation data search engines read, and the engine's facts sheet. B7R Print.
   */
  brandNameLatin: string;
  /**
   * The one-line definition: under the logo in the footer, the first line of llms.txt, the web app manifest, and the engine's facts sheet. The same sentence everywhere.
   */
  tagline: string;
  /**
   * How to reach us: the footer, the contact page, the WhatsApp widget and the organisation data.
   */
  contact: {
    /**
     * The number as a visitor sees it in the footer and on the contact page: 0501699572.
     */
    phone: string;
    /**
     * The international number the phone dials on a tap, and the organisation data: +966501699572.
     */
    phoneIntl: string;
    /**
     * The WhatsApp digits, no + and no spaces, for the wa.me link in the widget and every WhatsApp button: 966501699572.
     */
    whatsapp: string;
    /**
     * The e-mail in the footer and on the contact page, and the mailto link on a tap: contact@b7r.sa.
     */
    email: string;
  };
  /**
   * The official accounts: the footer and phone-menu icons, and the sameAs links in the organisation data. Real links only.
   */
  social: {
    /**
     * The full X profile link: https://x.com/b7rprint
     */
    x: string;
    /**
     * The full Instagram profile link: https://instagram.com/b7rprint
     */
    instagram: string;
    /**
     * The full TikTok profile link: https://tiktok.com/@b7rprint
     */
    tiktok: string;
  };
  menu: {
    /**
     * The header links in order, the phone menu, and the "Links" column of the footer.
     */
    primary: {
      /**
       * The link text in the header, the phone menu and the "Links" column of the footer.
       */
      label: string;
      /**
       * The path the link opens, starting with /: /products. The English site adds /en by itself.
       */
      href: string;
      /**
       * The link stays marked as the current one on every page whose path starts with this. Example: /products
       */
      matchPrefix?: string | null;
      id?: string | null;
    }[];
    /**
     * The "Policies" column of the footer: terms, shipping, privacy, FAQ.
     */
    policies: {
      /**
       * The link text in the "Policies" column of the footer.
       */
      label: string;
      /**
       * The path the link opens, starting with /: /privacy.
       */
      href: string;
      /**
       * The link stays marked as the current one on every page whose path starts with this. Example: /products
       */
      matchPrefix?: string | null;
      id?: string | null;
    }[];
    /**
     * The blue button in the header and in the phone menu.
     */
    ctaLabel: string;
    /**
     * The link a keyboard user sees on the first Tab, jumping past the header to the content.
     */
    skipLinkLabel: string;
    /**
     * What a screen reader calls the phone menu's burger while the menu is closed.
     */
    menuOpenLabel: string;
    /**
     * What a screen reader calls the phone menu's button while the menu is open.
     */
    menuCloseLabel: string;
  };
  /**
   * The welcome credit in SAR: the credit line in the About facts band and llms.txt. Must equal the app's: there is no sync.
   */
  welcomeCredit: number;
  /**
   * The most days a delivery takes inside the Kingdom: the "within N days" promise in llms.txt, the shipping data search engines read, and the engine facts sheet. Must equal the app: there is no sync.
   */
  deliveryMaxDays: number;
  /**
   * The shipping city: the map-pin chip in the About facts band, the shipping line of llms.txt, the organisation's address for search engines, and the engine's facts sheet: Jeddah.
   */
  deliveryOrigin: string;
  /**
   * The origin region in the organisation data search engines read (addressRegion): Makkah Region. Not shown to a visitor.
   */
  deliveryRegion: string;
  /**
   * The consultation booking link (Cal.com) for the contact page booking card. Empty opens WhatsApp with the prefilled message instead.
   */
  bookingUrl?: string | null;
  /**
   * Read by nothing on the site today: the footer's copyright line and the legal pages carry their own fixed text. Kept for the day they read it.
   */
  legalEntity: string;
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Search titles and descriptions for the fixed pages, and the default share image.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults".
 */
export interface SeoDefault {
  id: number;
  /**
   * The browser tab and the Google result title of every page: %s becomes the page title itself. Keep the part after the bar under 15 characters.
   */
  titleTemplate: string;
  /**
   * One row per fixed page: its search title, its description and the date its content last changed.
   */
  routes: {
    /**
     * The fixed page this row is for: /, /products or /blog.
     */
    route: string;
    /**
     * The date the page content last really changed: the sitemap lastmod for this route (search engines recrawl on it).
     */
    updatedAt: string;
    /**
     * The search result's title and the browser tab for this route; the site name from the template is appended. Up to 70 characters.
     */
    title: string;
    /**
     * The description under the title in the Google result for this route. One or two sentences, up to 155 characters.
     */
    description: string;
    /**
     * The share image's path for this route: /og/products.png. Empty uses /og/default.png.
     */
    ogImage?: string | null;
    id?: string | null;
  }[];
  /**
   * The tokens Google Search Console and Bing Webmaster Tools gave you to prove ownership (meta tags on the home page). Empty uses the environment variables.
   */
  verification?: {
    /**
     * Google Search Console's verification token (a meta tag on the home page). Empty uses the environment variable.
     */
    google?: string | null;
    /**
     * Bing Webmaster Tools' verification token (a meta tag on the home page). Empty uses the environment variable.
     */
    bing?: string | null;
  };
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The engine publishes without a human step (D-44). Unreviewed high-volume AI publishing risks the scaled-content policy of Google: keep the cadence moderate and the quality gates strict.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-settings".
 */
export interface AiSetting {
  id: number;
  /**
   * The connection the engine writes with: its key, model, rates and monthly limit live on the Connections page. With none, or with an off one, the engine refuses every run and says so on the dashboard.
   */
  connection?: (number | null) | Connection;
  /**
   * The kill switch. Off, no new run starts within the hour.
   */
  enabled?: boolean | null;
  /**
   * The research-backed range: 8 to 16 posts a month; quality before quantity.
   */
  postsPerDay: number;
  /**
   * The hour in Riyadh time (0 to 23) before which a scheduled run does not start that day; "Generate now" ignores it.
   */
  publishHourRiyadh: number;
  /**
   * The most posts the engine publishes in a month; then it waits for the next month.
   */
  maxPostsPerMonth: number;
  /**
   * The most the engine may spend in a day, in USD (estimated from the connection's rates); a run is refused once reached, until tomorrow. The monthly limit sits on the connection itself.
   */
  dailyCostCapUsd: number;
  /**
   * While above zero the posts of a live provider land as drafts for your read; set it to 0 once they read well.
   */
  reviewFirstRuns: number;
  style: {
    /**
     * The style guide the model reads before every post: tone, audience, what to say and what not to.
     */
    styleGuide: string;
    /**
     * The model's standing instructions for every run. Changing it bumps the version number the runs record.
     */
    systemPrompt: string;
    systemPromptVersion?: number | null;
    /**
     * Phrases a sentence may not start with, one per line; each costs 5 points in the self-review (25 at most).
     */
    bannedPhrases: string;
    /**
     * Claims the engine may never make (certifications, unproven numbers), one per line.
     */
    bannedClaims: string;
  };
  images: {
    /**
     * Generation is refused until an image provider is wired; Pexels needs a key.
     */
    imageMode: 'hubDefault' | 'stock' | 'generate';
    /**
     * Words appended to the Pexels search for a cover: "studio, white background". Empty searches by the title alone.
     */
    imageStyle?: string | null;
    /**
     * Stored encrypted and never shown again; leave the mask to keep it, clear it to remove it.
     */
    pexelsKey?: string | null;
  };
  quality: {
    /**
     * The lowest score (0 to 100) the self-review accepts; below it the post is rewritten or refused.
     */
    qualityThreshold: number;
    /**
     * How many times a post below the threshold is rewritten before it is refused.
     */
    maxRevisionPasses: number;
    /**
     * The fewest words a post should have; shorter loses 10 points in the self-review.
     */
    minWords: number;
    /**
     * The most words a post should have; longer loses 10 points in the self-review.
     */
    maxWords: number;
  };
  notifications?: {
    /**
     * Gets failure alerts and the weekly digest.
     */
    notifyEmail?: string | null;
    /**
     * A weekly e-mail to the notification address: what was published, what failed, the cost.
     */
    weeklyDigest?: boolean | null;
    /**
     * An e-mail to the notification address as soon as a run fails.
     */
    failureAlerts?: boolean | null;
  };
  /**
   * Who saved the current version and when. Drafts do not change it.
   */
  lastSavedBy?: {
    name?: string | null;
    at?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        slides?:
          | T
          | {
              headline?: T;
              subline?: T;
              imageDesktop?: T;
              imageMobile?: T;
              id?: T;
            };
        overlay?:
          | T
          | {
              enabled?: T;
              color?: T;
            };
        primaryCta?: T;
        secondaryCta?: T;
        microcopy?: T;
        chips?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  productStrip?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        pricePrefix?: T;
        button?: T;
        products?: T;
      };
  designer?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        cta?: T;
      };
  steps?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        link?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              icon?: T;
              id?: T;
            };
      };
  video?:
    | T
    | {
        enabled?: T;
        title?: T;
        lead?: T;
      };
  whyUs?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              text?: T;
              id?: T;
            };
      };
  testimonials?:
    | T
    | {
        enabled?: T;
        eyebrow?: T;
        title?: T;
      };
  integrations?:
    | T
    | {
        enabled?: T;
        title?: T;
        lead?: T;
      };
  faq?:
    | T
    | {
        enabled?: T;
        title?: T;
        link?: T;
      };
  ribbon?:
    | T
    | {
        title?: T;
        lead?: T;
        button?: T;
      };
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  brandNameLatin?: T;
  tagline?: T;
  contact?:
    | T
    | {
        phone?: T;
        phoneIntl?: T;
        whatsapp?: T;
        email?: T;
      };
  social?:
    | T
    | {
        x?: T;
        instagram?: T;
        tiktok?: T;
      };
  menu?:
    | T
    | {
        primary?:
          | T
          | {
              label?: T;
              href?: T;
              matchPrefix?: T;
              id?: T;
            };
        policies?:
          | T
          | {
              label?: T;
              href?: T;
              matchPrefix?: T;
              id?: T;
            };
        ctaLabel?: T;
        skipLinkLabel?: T;
        menuOpenLabel?: T;
        menuCloseLabel?: T;
      };
  welcomeCredit?: T;
  deliveryMaxDays?: T;
  deliveryOrigin?: T;
  deliveryRegion?: T;
  bookingUrl?: T;
  legalEntity?: T;
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-defaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  titleTemplate?: T;
  routes?:
    | T
    | {
        route?: T;
        updatedAt?: T;
        title?: T;
        description?: T;
        ogImage?: T;
        id?: T;
      };
  verification?:
    | T
    | {
        google?: T;
        bing?: T;
      };
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-settings_select".
 */
export interface AiSettingsSelect<T extends boolean = true> {
  connection?: T;
  enabled?: T;
  postsPerDay?: T;
  publishHourRiyadh?: T;
  maxPostsPerMonth?: T;
  dailyCostCapUsd?: T;
  reviewFirstRuns?: T;
  style?:
    | T
    | {
        styleGuide?: T;
        systemPrompt?: T;
        systemPromptVersion?: T;
        bannedPhrases?: T;
        bannedClaims?: T;
      };
  images?:
    | T
    | {
        imageMode?: T;
        imageStyle?: T;
        pexelsKey?: T;
      };
  quality?:
    | T
    | {
        qualityThreshold?: T;
        maxRevisionPasses?: T;
        minWords?: T;
        maxWords?: T;
      };
  notifications?:
    | T
    | {
        notifyEmail?: T;
        weeklyDigest?: T;
        failureAlerts?: T;
      };
  lastSavedBy?:
    | T
    | {
        name?: T;
        at?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskIndexnow-ping".
 */
export interface TaskIndexnowPing {
  input: {
    urls:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output: {
    status?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskContent-tick".
 */
export interface TaskContentTick {
  input?: unknown;
  output: {
    queued?: boolean | null;
    reason?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskContent-freshness".
 */
export interface TaskContentFreshness {
  input?: unknown;
  output: {
    checked?: number | null;
    queued?: number | null;
    reason?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskContent-digest".
 */
export interface TaskContentDigest {
  input?: unknown;
  output: {
    sent?: boolean | null;
    deleted?: number | null;
    reason?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'products';
          value: number | Product;
        } | null)
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'testimonials';
          value: number | Testimonial;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: 'home' | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowGeneratePost".
 */
export interface WorkflowGeneratePost {
  input: {
    topicId?: number | null;
    manual?: boolean | null;
    replacePostId?: number | null;
    kind?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}