import type { DefaultTranslationsObject } from '@payloadcms/translations';

type DeepPartial<T> = { [K in keyof T]?: T[K] extends object ? DeepPartial<T[K]> : T[K] };

/**
 * Our Arabic on top of Payload's (ADR-056). Payload's `ar` pack is community work: the
 * strings an editor meets every day carry «تم» + مصدر, «قم بـ», wrong hamzas («أنشاء»),
 * mistranslations («واضح» for clear, «المواقع» for locales), an
 * untranslated «Toggle block», a translated placeholder («{{العنوان}}») and one string that
 * is a leaked instruction to a translation model (`general.restoring`). These entries are
 * merged over the pack by `i18n.translations.ar` in the config (`deepMergeSimple`: a key
 * here wins, the rest stays Payload's), written under the ux-araby rules (design system §5).
 * «اللغة» is split on purpose: `general.language` is the panel's language (the account
 * view), `general.locale` the content's (the switcher), so the two controls never read alike.
 */
export const payloadArabic: DeepPartial<DefaultTranslationsObject> = {
  authentication: {
    beginCreateFirstUser: 'للبدء، أنشئ المستخدم الأول.',
    emailSent: 'أُرسل البريد الإلكتروني.',
    forgotPasswordEmailInstructions:
      'أدخل بريدك الإلكتروني أدناه، وستصلك رسالة بخطوات إعادة تعيين كلمة المرور.',
    loggedOutInactivity: 'سُجّل خروجك لعدم النشاط.',
    loggedOutSuccessfully: 'سُجّل خروجك.',
    logoutSuccessful: 'سُجّل خروجك.',
    passwordResetSuccessfully: 'أُعيد تعيين كلمة المرور.',
    verify: 'تحقّق',
    verifyUser: 'تحقّق من المستخدم',
    verifyYourEmail: 'أكّد بريدك الإلكتروني',
    youAreInactive: 'لم تكن نشطاً منذ فترة، وسيُسجّل خروجك تلقائياً قريباً حمايةً لحسابك. أتريد البقاء؟',
  },
  error: {
    autosaving: 'تعذّر الحفظ التلقائي لهذا المستند.',
    correctInvalidFields: 'صحّح الحقول المعلّمة.',
    deletingTitle: 'تعذّر حذف {{title}}. تحقق من اتصالك وحاول مرة أخرى.',
    documentNotFound:
      'لم نجد المستند ذا المعرّف {{id}}. ربما حُذف، أو لم يكن موجوداً، أو لا صلاحية لك عليه.',
    emailOrPasswordIncorrect: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
    noFilesUploaded: 'لم يُرفع أي ملف.',
    notAllowedToAccessPage: 'لا يُسمح لك بالوصول إلى هذه الصفحة.',
    notAllowedToPerformAction: 'لا يُسمح لك بهذا الإجراء.',
    previewing: 'تعذّرت معاينة هذا المستند.',
    problemUploadingFile: 'تعذّر رفع الملف.',
    unauthorized: 'غير مصرّح لك؛ سجّل الدخول أولاً.',
    unPublishingDocument: 'تعذّر إلغاء نشر هذا المستند.',
    userLocked: 'قُفل هذا الحساب بعد محاولات دخول فاشلة كثيرة.',
  },
  fields: {
    addLink: 'أضف رابطاً',
    addNew: 'أضف جديداً',
    addUpload: 'أضف ملفاً',
    linkedTo: 'مرتبط بـ<0>{{label}}</0>',
    passwordsDoNotMatch: 'كلمتا المرور غير متطابقتين.',
    removeUpload: 'إزالة الملف',
    swapUpload: 'تبديل الملف',
    toggleBlock: 'طيّ الكتلة أو فتحها',
  },
  general: {
    aboutToDelete: 'ستحذف {{label}} <1>{{title}}</1>. أتريد المتابعة؟',
    aboutToDeleteCount_many: 'ستحذف {{count}} {{label}}',
    aboutToDeleteCount_one: 'ستحذف {{count}} {{label}}',
    aboutToDeleteCount_other: 'ستحذف {{count}} {{label}}',
    aboutToTrash: 'ستنقل {{label}} <1>{{title}}</1> إلى سلة المهملات. أتريد المتابعة؟',
    addFilter: 'أضف عامل تصفية',
    adminTheme: 'مظهر اللوحة',
    allLocales: 'كل لغات المحتوى',
    anotherUserTakenOver: 'تولّى مستخدم آخر تحرير هذا المستند.',
    applyChanges: 'طبّق التغييرات',
    changesNotSaved: 'التغييرات غير محفوظة. إن غادرت الآن فستفقدها.',
    clear: 'مسح',
    confirmDuplication: 'تأكيد النسخ',
    copied: 'نُسخ',
    copyWarning: 'ستستبدل {{to}} بـ{{from}} في {{label}} {{title}}. أتريد المتابعة؟',
    created: 'أُنشئ',
    createdAt: 'تاريخ الإنشاء',
    createNew: 'إنشاء جديد',
    creating: 'جارٍ الإنشاء…',
    creatingNewLabel: 'إنشاء {{label}} جديد',
    currentlyEditing:
      'يحرر هذا المستند الآن. إن تولّيت التحرير فسيُمنع من المتابعة وقد يفقد تغييراته غير المحفوظة.',
    deleted: 'محذوف',
    deletedAt: 'تاريخ الحذف',
    deletedCountSuccessfully: 'حُذف {{count}} {{label}}.',
    deletedSuccessfully: 'حُذف.',
    deletePermanently: 'احذف نهائياً دون المرور بسلة المهملات',
    deleting: 'جارٍ الحذف…',
    documentIsTrashed: 'هذا {{label}} في سلة المهملات، للقراءة فقط.',
    documentLocked: 'المستند مقفل',
    documentModified: 'عُدّل المستند',
    documentOutOfDate: 'حدّث مستخدم آخر هذا المستند للتو؛ ما تراه قديم.',
    duplicate: 'إنشاء نسخة',
    duplicateWithoutSaving: 'إنشاء نسخة دون حفظ التغييرات',
    editedSince: 'عُدّل منذ',
    editing: 'تحرير',
    editingTakenOver: 'انتقل التحرير إلى مستخدم آخر',
    emptyTrash: 'أفرغ سلة المهملات',
    false: 'لا',
    language: 'لغة اللوحة',
    loading: 'جارٍ التحميل…',
    locale: 'لغة المحتوى',
    locales: 'لغات المحتوى',
    move: 'نقل',
    moving: 'جارٍ النقل…',
    noDateSelected: 'لم يُختر تاريخ',
    noFiltersSet: 'لا عوامل تصفية',
    noResults: 'لا {{label}} بعد، أو لا شيء يطابق عوامل التصفية أعلاه.',
    nothingFound: 'لا نتائج',
    noValue: 'لا قيمة',
    permanentlyDelete: 'حذف نهائي',
    permanentlyDeletedCountSuccessfully: 'حُذف {{count}} {{label}} نهائياً.',
    resettingPreferences: 'جارٍ إعادة التعيين…',
    restoredCountSuccessfully: 'استُعيد {{count}} {{label}}.',
    restoring: 'جارٍ الاستعادة…',
    saving: 'جارٍ الحفظ…',
    schedulePublishFor: 'جدولة النشر لـ{{title}}',
    searchBy: 'البحث في {{label}}',
    selectedCount: 'المحدد: {{count}} {{label}}',
    selectValue: 'اختر قيمة',
    sorryNotFound: 'لا شيء يطابق طلبك.',
    submissionSuccessful: 'أُرسل.',
    submitting: 'جارٍ الإرسال…',
    success: 'نجاح',
    successfullyCreated: 'أُنشئ {{label}}.',
    successfullyDuplicated: 'نُسخ {{label}}.',
    takeOver: 'تولّي التحرير',
    titleDeleted: 'حُذف {{label}} «{{title}}».',
    titleRestored: 'استُعيد {{label}} «{{title}}».',
    titleTrashed: 'نُقل {{label}} «{{title}}» إلى سلة المهملات.',
    trashedCountSuccessfully: 'نُقل {{count}} {{label}} إلى سلة المهملات.',
    true: 'نعم',
    unlock: 'فتح القفل',
    unsavedChanges: 'لديك تغييرات غير محفوظة. احفظها أو تجاهلها قبل المتابعة.',
    unsavedChangesDuplicate: 'لديك تغييرات غير محفوظة. أتريد إنشاء النسخة على أي حال؟',
    updatedAt: 'تاريخ التحديث',
    updatedCountSuccessfully: 'حُدّث {{count}} {{label}}.',
    updatedLabelSuccessfully: 'حُفظ {{label}}.',
    updatedSuccessfully: 'حُفظت التغييرات.',
    updating: 'جارٍ التحديث…',
    uploading: 'جارٍ الرفع…',
    uploadingBulk: 'جارٍ رفع {{current}} من {{total}}',
    users: 'المستخدمون',
  },
  localization: {
    cannotCopySameLocale: 'لا يمكن النسخ إلى اللغة نفسها',
    copyTo: 'نسخ إلى',
    copyToLocale: 'نسخ إلى لغة أخرى',
    localeToPublish: 'لغة النشر',
    selectedLocales: 'اللغات المحددة',
    selectLocaleToCopy: 'اختر اللغة للنسخ إليها',
    selectLocaleToDuplicate: 'اختر اللغات للنسخ',
  },
  operators: {
    isLike: 'يشبه',
    isNotLike: 'لا يشبه',
    within: 'ضمن',
  },
  upload: {
    addFile: 'أضف ملفاً',
    bulkUpload: 'رفع دفعة',
    download: 'تنزيل',
    dragAndDrop: 'اسحب ملفاً وأفلته',
    filesToUpload: 'ملفات للرفع',
    fileToUpload: 'ملف للرفع',
    selectFile: 'اختر ملفاً',
  },
  validation: {
    emailAddress: 'أدخل بريداً إلكترونياً صحيحاً.',
    enterNumber: 'أدخل رقماً صحيحاً.',
    greaterThanMax: '{{value}} أكبر من الحد الأقصى لـ{{label}}: {{max}}.',
    invalidInput: 'القيمة غير صالحة.',
    invalidSelection: 'الاختيار غير صالح.',
    lessThanMin: '{{value}} أقل من الحد الأدنى لـ{{label}}: {{min}}.',
    limitReached: 'بلغت الحد الأقصى: {{max}} عناصر فقط.',
    longerThanMin: '{{minLength}} أحرف على الأقل.',
    requiresAtLeast: 'يلزم {{count}} {{label}} على الأقل.',
    requiresNoMoreThan: '{{count}} {{label}} على الأكثر.',
    requiresTwoNumbers: 'يلزم رقمان.',
    shorterThanMax: '{{maxLength}} حرفاً على الأكثر.',
    username: 'أدخل اسم مستخدم صالحاً: أحرف وأرقام وشرطات ونقاط وشرطات سفلية.',
  },
  version: {
    aboutToPublishSelection: 'ستنشر كل {{label}} المحددة. أتريد المتابعة؟',
    aboutToRestore: 'ستُعيد {{label}} إلى حالته في {{versionDate}}.',
    aboutToRestoreGlobal: 'ستُعيد {{label}} إلى حالته في {{versionDate}}.',
    aboutToRevertToPublished: 'ستُعيد هذا المستند إلى نسخته المنشورة. أتريد المتابعة؟',
    aboutToUnpublish: 'ستُلغي نشر هذا المستند. أتريد المتابعة؟',
    aboutToUnpublishIn: 'ستُلغي نشر هذا المستند بلغة {{locale}}. أتريد المتابعة؟',
    aboutToUnpublishSelection: 'ستُلغي نشر كل {{label}} المحددة. أتريد المتابعة؟',
    autosavedSuccessfully: 'حُفظت تلقائياً.',
    changed: 'تغيّر',
    changedFieldsCount_one: 'تغيّر حقل واحد',
    changedFieldsCount_other: 'تغيّر {{count}} حقول',
    compareVersions: 'قارن النسخ',
    confirmVersionRestoration: 'تأكيد استعادة النسخة',
    currentDocumentStatus: 'حالة المستند: {{docStatus}}',
    currentlyPublished: 'منشور حالياً',
    currentlyViewing: 'المعروض حالياً',
    draftHasPublishedVersion: 'مسودة (لها نسخة منشورة)',
    draftSavedSuccessfully: 'حُفظت المسودة.',
    lastSavedAgo: 'آخر حفظ قبل {{distance}}',
    modifiedOnly: 'المعدّلة فقط',
    moreVersions: 'مزيد من النسخ…',
    noFurtherVersionsFound: 'لا نسخ أخرى',
    noRowsFound: 'لا {{label}}',
    noRowsSelected: 'لم يُحدد {{label}}',
    previouslyDraft: 'مسودة سابقاً',
    previouslyPublished: 'منشور سابقاً',
    problemRestoringVersion: 'تعذّرت استعادة هذه النسخة.',
    publishAllLocales: 'نشر كل اللغات',
    published: 'منشور',
    publishing: 'جارٍ النشر…',
    restoredSuccessfully: 'استُعيدت النسخة.',
    restoring: 'جارٍ الاستعادة…',
    reverting: 'جارٍ الرجوع…',
    revertUnsuccessful: 'تعذّر الرجوع: لا نسخة منشورة سابقة.',
    scheduledSuccessfully: 'جُدول النشر.',
    schedulePublish: 'جدولة النشر',
    showingVersionsFor: 'النسخ لـ:',
    showLocales: 'أظهر اللغات:',
    specificVersion: 'النسخة المحددة',
    unpublish: 'إلغاء النشر',
    unpublishedSuccessfully: 'أُلغي النشر.',
    unpublishing: 'جارٍ إلغاء النشر…',
    versionAgo: 'قبل {{distance}}',
    versionCount_many: '{{count}} نسخة',
    versionCount_none: 'لا نسخ',
    versionCount_one: 'نسخة واحدة',
    versionCount_other: '{{count}} نُسخ',
    viewingVersion: 'نسخة من {{entityLabel}} {{documentTitle}}',
    viewingVersionGlobal: 'نسخة من {{entityLabel}}',
    viewingVersions: 'نسخ {{entityLabel}} {{documentTitle}}',
    viewingVersionsGlobal: 'نسخ {{entityLabel}}',
  },
};
