/**
 * The shell's interface strings (ADR-031: interface copy is ours). The panel is English
 * (Dhia, 2026-09-13); the content it edits stays Arabic. Payload's own strings come from its
 * `en` pack. No em dashes (.claude/rules/writing.md).
 */
export const adminStrings = {
  nav: {
    label: 'Main navigation',
    brand: 'B7R Print Website',
    expand: 'Expand the sidebar',
    collapse: 'Collapse the sidebar',
    closeMenu: 'Close the menu',
    groupToggle: 'collapse or expand the group',
    viewSite: 'View website',
  },
  header: {
    search: 'Search or jump to…',
    searchAria: 'Search or jump to a section',
    viewSite: 'View website',
  },
  account: {
    menu: 'Account menu',
    profile: 'My account',
    logout: 'Log out',
    roles: { admin: 'Admin', editor: 'Editor' } as Record<string, string>,
  },
  palette: {
    title: 'Jump to…',
    placeholder: 'Type a section, a page or a product',
    hint: 'Type two characters or more to search the content',
    sections: 'Sections',
    results: 'Content',
    empty: 'Nothing matches.',
    open: 'open',
    shortcut: 'Press Ctrl K anywhere',
    searching: 'Searching…',
    status: { draft: 'Draft', published: 'Published' } as Record<string, string>,
  },
  login: {
    noAccount: 'No account? Ask the site admin for one.',
  },
  savedBy: {
    by: 'by',
    never: 'No save recorded yet.',
  },
  warnings: {
    none: 'Nothing to flag.',
  },
  engine: {
    generateNow: 'Generate now',
    queueing: 'Queueing…',
    queued: 'Queued: the run starts within a minute. Watch the runs list.',
    postTitle: 'Content engine',
    regenerate: 'Regenerate',
    regenerateHint: 'A new run from the topic replaces the text under the same address and cover.',
    importTitle: 'Bulk add from CSV',
    importHint:
      'Columns: title, hub (slug), primaryKeyword, secondaryKeywords (separated by ;), intent, priority. A header row is fine.',
    importPlaceholder: 'title,hub,primaryKeyword,secondaryKeywords,intent,priority',
    importButton: 'Import',
    importing: 'Importing…',
    importResult: '{created} added, {skipped} already there.',
    factsTitle: 'What the engine may say',
    factsHint:
      'Built live from the site settings, the products and the integrations, in Arabic and in English; every number a draft states is checked against this list.',
    factsNumbers: '{n} numbers on the sheet.',
    card: {
      title: 'Content engine',
      off: 'Off',
      on: 'On',
      mock: 'Mock provider',
      postsThisMonth: 'Posts this month',
      averageScore: 'Average score',
      failures: 'Failed runs',
      cost: 'Cost this month (estimate)',
      nextSlot: 'Next slot',
      nextSlotOff: 'No run while the engine is off',
      nextSlotToday: 'Today at {hour}:00 Riyadh',
      nextSlotTomorrow: 'Tomorrow at {hour}:00 Riyadh',
      nextSlotDone: 'Done for today; tomorrow at {hour}:00 Riyadh',
      nextSlotSoon: 'Within the hour',
      recent: 'Latest runs',
      empty: 'No run yet. Add topics and switch the engine on, or press "Generate now" on a topic.',
      settings: 'Settings',
      topics: 'Topics',
      runs: 'Runs',
    },
  },
  dashboard: {
    greeting: 'Welcome, {name}',
    intro: 'Everything on the site starts here.',
    quick: 'Start here',
    actions: {
      home: { title: 'Home page', text: 'Edit the sections and publish' },
      addPage: { title: 'Add a page', text: 'A new page with its own URL' },
      addProduct: { title: 'Add a product', text: 'Prices, photos and sizes' },
      addFaq: { title: 'Add a question', text: 'A new entry in the FAQ' },
      addPost: { title: 'Write a post', text: 'A new article on the blog' },
      site: { title: 'View website', text: 'As a visitor sees it' },
    },
    health: {
      title: 'System status',
      engine: {
        on: 'Content engine on',
        off: 'Content engine off',
        mock: 'Content engine on (mock provider)',
      },
      check: 'Full report',
      version: 'Version',
      rows: {
        db: { ok: 'Database answering', error: 'Database not answering' },
        jobs: { on: 'Scheduled jobs running', off: 'Scheduled jobs not started yet' },
        jobsFailed: {
          none: 'No failed jobs',
          some: '{n} failed jobs',
          unknown: 'Job status unknown',
        },
        email: {
          resend: 'E-mail goes out through Resend',
          console: 'E-mail printed to the log, no provider',
        },
        turnstile: { on: 'Bot check on', off: 'Bot check off' },
        indexnow: { on: 'Search-engine pings on', off: 'Search-engine pings off' },
        media: { s3: 'Media on cloud storage', local: 'Media on the server disk' },
        contact: {
          live: 'Contact form sending',
          mock: 'Contact form in test mode',
          off: 'Contact form off',
        },
        newsletter: {
          live: 'Newsletter recording subscribers',
          mock: 'Newsletter in test mode',
          off: 'Newsletter off',
        },
      },
    },
    recent: {
      title: 'Latest changes',
      empty: 'No changes yet. Start with the home page.',
      by: 'by {name}',
      draft: 'Draft',
      published: 'Published',
    },
  },
} as const;
